Repository tier4/scenario_simulator_v2, pull requests merged in 2021-04, with the labels that each got.

#262 Feature/interpreter/traffic signal controller 2
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/iterator/circular_iterator.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/arrow.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/catalog_location.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/catalog_locations.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/color.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/file.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/phase.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/road_network.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
  openscenario/openscenario_interpreter/src/procedure.cpp
  openscenario/openscenario_interpreter/src/syntax/arrow.cpp
  openscenario/openscenario_interpreter/src/syntax/color.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
  test_runner/scenario_test_runner/test/scenario/Autoware.TrafficSignals.yaml
Labels: feature

#264 Revert "enable interpolate two points"
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
Labels: bug

#263 Feature/traffic signal sensor
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/color_utils/color_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_phase.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_state.hpp
  simulation/traffic_simulator/src/color_utils/color_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_state.cpp
  test_runner/scenario_test_runner/test/scenario/Autoware.TrafficSignals.yaml
Labels: feature

#267 Doc/simple sensor simulator
  docs/design/SimpleSensorSimulator.md
  docs/image/simple_sensor_simulator.png
  docs/package/About.md
  docs/package/simulation_interface/.gitignore
  docs/package/simulation_interface/Doxyfile
  docs/package/simulation_interface/build.sh
  docs/package/simulation_interface/config.json
  mkdocs.yml
Labels: documentation

#268 configure settings of documentation
  .github/workflows/Documentation.yaml
  docs/package/simple_sensor_simulator/config.json
Labels: bug, documentation

#271 Feature/change base image
  Dockerfile
  load_image.sh
  save_image.sh
Labels: feature

#275 Feature/init duration
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/exception.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: feature

#274 Refactor/cleanup ego entity
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/exception.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: refactor

#277 Doc/docker
  .github/workflows/Build.yaml
  .github/workflows/Docker.yaml
  Dockerfile
  docker-entrypoint.sh
  docs/README.md
  docs/image/rviz_with_rocker.png
  docs/tutorials/RunWithDocker.md
  make_docs.sh
  mkdocs.yml
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: feature

#276 Feature/autoware high level api
  external/awapi_accessor/CMakeLists.txt
  external/awapi_accessor/include/awapi_accessor/accessor.hpp
  external/awapi_accessor/include/awapi_accessor/autoware.hpp
  external/awapi_accessor/include/awapi_accessor/autoware_error.hpp
  external/awapi_accessor/include/awapi_accessor/continuous_transform_broadcaster.hpp
  external/awapi_accessor/include/awapi_accessor/conversion.hpp
  external/awapi_accessor/include/awapi_accessor/define_macro.hpp
  external/awapi_accessor/include/awapi_accessor/execute.hpp
  external/awapi_accessor/include/awapi_accessor/fundamental_api.hpp
  external/awapi_accessor/include/awapi_accessor/launch.hpp
  external/awapi_accessor/include/awapi_accessor/miscellaneous_api.hpp
  external/awapi_accessor/include/awapi_accessor/transition_assertion.hpp
  external/awapi_accessor/include/awapi_accessor/utility/visibility.hpp
  external/awapi_accessor/src/autoware.cpp
  external/awapi_accessor/src/execute.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: feature

#279 Fix/push docker image workflow
  .github/workflows/Build.yaml
  .github/workflows/Docker.yaml
  README.md
Labels: feature

#280 add push trigger
  .github/workflows/Docker.yaml
  README.md
  docs/README.md
Labels: feature

#282 update document
  docs/tutorials/RunWithDocker.md
Labels: documentation

#281 Feature/asynchronous autoware initialization
  .github/workflows/Docker.yaml
  external/awapi_accessor/include/awapi_accessor/autoware.hpp
  external/awapi_accessor/include/awapi_accessor/continuous_transform_broadcaster.hpp
  external/awapi_accessor/include/awapi_accessor/launch.hpp
  external/awapi_accessor/include/awapi_accessor/task_queue.hpp
  external/awapi_accessor/include/awapi_accessor/transition_assertion.hpp
  external/awapi_accessor/src/autoware.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/exception.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  test_runner/scenario_test_runner/test/scenario/Autoware.Curve.yaml
  test_runner/scenario_test_runner/test/scenario/Autoware.TrafficSignals.yaml
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: feature

#289 Feature/update contact information
  docs/etc/ContactUs.md
  docs/stylesheet/tierivcolor.css
  mkdocs.yml
Labels: documentation

#287 Feature/remove dummy perception publisher
  .github/workflows/Docker.yaml
  external/awapi_accessor/include/awapi_accessor/task_queue.hpp
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_error.hpp
  external/concealer/include/concealer/continuous_transform_broadcaster.hpp
  external/concealer/include/concealer/conversion.hpp
  external/concealer/include/concealer/define_macro.hpp
  external/concealer/include/concealer/execute.hpp
  external/concealer/include/concealer/fundamental_api.hpp
  external/concealer/include/concealer/launch.hpp
  external/concealer/include/concealer/miscellaneous_api.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/include/concealer/undefine_macro.hpp
  external/concealer/include/concealer/utility/visibility.hpp
  external/concealer/package.xml
  external/concealer/src/autoware.cpp
  external/concealer/src/execute.cpp
  external/concealer/src/task_queue.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/package.xml
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#290 add release action
  .github/workflows/Release.yaml
Labels: feature

#291 remove unused package
  external/awapi_awauto_adapter/CMakeLists.txt
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/autoware_auto_adapter.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/awapi_awauto_status_publisher.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/awapi_lane_change_status_publisher.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/awapi_obstacle_avoidance_status_publisher.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/awapi_simulation_api_publisher.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/awapi_vehicle_status_publisher.hpp
  external/awapi_awauto_adapter/include/awapi_awauto_adapter/utility/visibility.h
  external/awapi_awauto_adapter/package.xml
  external/awapi_awauto_adapter/src/awapi_awauto_adapter.cpp
  external/awapi_awauto_adapter/src/awapi_awauto_adapter_node.cpp
  external/awapi_awauto_adapter/src/awapi_awauto_status_publisher.cpp
  external/awapi_awauto_adapter/src/awapi_lane_change_status_publisher.cpp
  external/awapi_awauto_adapter/src/awapi_obstacle_avoidance_status_publisher.cpp
  external/awapi_awauto_adapter/src/awapi_simulation_api_publisher.cpp
  external/awapi_awauto_adapter/src/awapi_vehicle_status_publisher.cpp
Labels: feature

#293 Disable emergency monitoring
  external/concealer/include/concealer/fundamental_api.hpp
Labels: small problem
