Repository tier4/scenario_simulator_v2, pull requests merged in 2021-08, with the labels that each got.

#429 Feature/add cpp scenarios
  .github/workflows/ScenarioTest.yaml
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/collision/CMakeLists.txt
  mock/cpp_mock_scenarios/src/collision/idiot_npc.cpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/lane_change/CMakeLists.txt
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
Labels: feature

#434 remove unused functions
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: small feature

#436 fix codecov.yml
  codecov.yml
Labels: bug

#420 Namespace
  docs/user_guide/scenario_test_runner/ScenarioTestRunner.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/iterator/circular_iterator.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/absolute_target_speed.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entities.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/file_header.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/misc_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/object_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_declaration.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_modify_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_set_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/pedestrian.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/private.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_target_speed.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/route.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action_target.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/story.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element_state_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_value_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
  test_runner/scenario_test_runner/test/scenario/TrafficSignalControllerAction.yaml
  test_runner/scenario_test_runner/test/scenario/TrafficSignals.yaml
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/test/scenario/parameter.yaml
Labels: feature

#430 Feature/interpreter/error message
  common/simple_junit/include/simple_junit/junit5.hpp
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_utility/requirements.txt
  openscenario/openscenario_utility/resource/openscenario_utility
  openscenario/openscenario_utility/setup.py
  test_runner/scenario_test_runner/scenario_test_runner/result_checker.py
  test_runner/scenario_test_runner/setup.cfg
Labels: feature, refactor

#440 Fix/follow front entity behavior
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/src/behavior/action_node.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
Labels: bug

#441 update release note
  docs/ReleaseNotes.md
Labels: release

#445 modify document
  RunTestScenarioWithDocker.md
  docs/tutorials/RunTestScenarioWithDocker.md
  docs/tutorials/RunWithDocker.md
Labels: bug, documentation

#447 source command
  docs/tutorials/SimpleDemo.md
Labels: bug, documentation

#446 Feature/out of range metric
  docs/ReleaseNotes.md
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
Labels: feature

#448 Feature/add cpp scenarios
  .github/workflows/ScenarioTest.yaml
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/traffic_light/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/metrics/metrics_manager.cpp
Labels: feature

#449 Fix path in building instruction
  docs/tutorials/BuildInstructions.md
Labels: documentation

#450 Fix/phase control
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: bug

#452 Fix/stop at crossing entity behavior
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/crosswalk/CMakeLists.txt
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  simulation/traffic_simulator/src/behavior/action_node.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
Labels: bug

#451 add OutOfRangeMetric when vehicle is spawned
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
Labels: feature

#453 update Release note
  docs/ReleaseNotes.md
Labels: release

#456 modify timeout
  .github/workflows/Build.yaml
  .github/workflows/ScenarioTest.yaml
Labels: small feature

#457 Feature/math test
  openscenario/openscenario_msgs/CMakeLists.txt
  openscenario/openscenario_msgs/msg/CatmullRomSpline.msg
  openscenario/openscenario_msgs/msg/EntityTrajectory.msg
  openscenario/openscenario_msgs/msg/HermiteCurve.msg
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/follow_front_entity_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/follow_lane_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/stop_at_stop_line_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/stop_at_traffic_light_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/yield_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/lane_change_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/vehicle_action_node.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/collision.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/test_math.cpp
Labels: bug

#444 Feature/interpreter/cleanup error messages
  common/scenario_simulator_exception/include/scenario_simulator_exception/exception.hpp
  external/concealer/include/concealer/define_macro.hpp
  external/concealer/include/concealer/miscellaneous_api.hpp
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/record.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/record.cpp
  test_runner/scenario_test_runner/config/scenario_simulator_v2.rviz
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/test/scenario/Property.isBlind.yaml
Labels: refactor

#459 Fix usage of uninitialized ZMQ API
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
Labels: bug

#460 update release note
  docs/ReleaseNotes.md
Labels: documentation

#461 Feature/move backward action
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/move_backward/CMakeLists.txt
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/follow_lane_sequence/move_backward_action.hpp
  simulation/traffic_simulator/resource/vehicle_entity_behavior.xml
  simulation/traffic_simulator/src/behavior/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/move_backward_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
Labels: feature

#463 modify release note
  docs/ReleaseNotes.md
Labels: documentation

#464 Feature/add math test
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/polynomial_solver.hpp
  simulation/traffic_simulator/src/math/collision.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/src/math/polynomial_solver.cpp
  simulation/traffic_simulator/src/math/uuid.cpp
  simulation/traffic_simulator/test/CMakeLists.txt
  simulation/traffic_simulator/test/src/math/CMakeLists.txt
  simulation/traffic_simulator/test/src/math/test_bounding_box.cpp
  simulation/traffic_simulator/test/src/math/test_catmull_rom_spline.cpp
  simulation/traffic_simulator/test/src/math/test_collision.cpp
  simulation/traffic_simulator/test/src/math/test_distance.cpp
  simulation/traffic_simulator/test/src/math/test_hermite_curve.cpp
  simulation/traffic_simulator/test/src/math/test_polynominal_solver.cpp
  simulation/traffic_simulator/test/src/math/test_uuid.cpp
  simulation/traffic_simulator/test/src/test_math.cpp
Labels: feature

#465 Feature/remove unused constructor
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
Labels: refactor

#468 Fix/fetch depth
  .github/workflows/Build.yaml
  .github/workflows/ScenarioTest.yaml
Labels: bug

#467 Feature/mock coverage
  .github/workflows/ScenarioTest.yaml
  mock/cpp_mock_scenarios/src/collision/idiot_npc.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
Labels: feature

#477 update release note
  docs/ReleaseNotes.md
Labels: release

#439 Feature/request acuire position in world coordinate
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_lane/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#483 update release note for PR #480 and #481
  docs/ReleaseNotes.md
Labels: documentation, release note

#484 add development rules
  docs/README.md
  docs/etc/DevelopmentRules.md
  mkdocs.yml
Labels: documentation
