Repository tier4/scenario_simulator_v2, pull requests merged in 2021-11, with the labels that each got.

#599 fix URL
  docs/README.md
Labels: bug, documentation

#600 fix git username
  .github/workflows/Release.yaml
Labels: bug

#597 Refactor/traffic simulator/spawning
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/measurement/get_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  mock/cpp_mock_scenarios/src/metrics/momentary_stop.cpp
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  mock/cpp_mock_scenarios/src/metrics/reaction_time.cpp
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/src/syntax/add_entity_action.cpp
  openscenario/openscenario_interpreter/src/syntax/teleport_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: refactor

#603 Fix/get s value
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/math/test_catmull_rom_spline.cpp
  simulation/traffic_simulator/test/src/math/test_hermite_curve.cpp
Labels: bug

#606 update Release note for releae 0.5.7
  docs/ReleaseNotes.md
Labels: release note

#609 enable pass behavior value in spawn function in API class
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
Labels: feature

#605 Refactor/interpreter/reference
  .github/workflows/ScenarioTest.yaml
  openscenario/openscenario_interpreter/include/openscenario_interpreter/name.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/src/scope.cpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/misc_object.cpp
  openscenario/openscenario_interpreter/src/syntax/pedestrian.cpp
  openscenario/openscenario_interpreter/src/syntax/route.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_object.cpp
  openscenario/openscenario_interpreter/src/syntax/story.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle.cpp
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/test/scenario/prefixed-name-reference.yaml
Labels: refactor

#611 Fix/documentation
  docs/user_guide/scenario_test_runner/ScenarioFormatConversion.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/src/autoware.cpp
Labels: documentation

#612 Feature/remove newton method from get s value
  .github/workflows/BuildIsolate.yaml
  docs/ReleaseNotes.md
  external/lanelet2_matching/CMakeLists.txt
  external/lanelet2_matching/README.md
  external/lanelet2_matching/custom.cmake
  external/lanelet2_matching/include/lanelet2_matching/Exceptions.h
  external/lanelet2_matching/include/lanelet2_matching/LaneletMatching.h
  external/lanelet2_matching/include/lanelet2_matching/Types.h
  external/lanelet2_matching/include/lanelet2_matching/Utilities.h
  external/lanelet2_matching/include/lanelet2_matching/internal/.gitignore
  external/lanelet2_matching/package.xml
  external/lanelet2_matching/src/.gitignore
  external/lanelet2_matching/src/LaneletMatching.cpp
  external/lanelet2_matching/src/Utilities.cpp
  external/lanelet2_matching/test/lanelet2_matching.cpp
  external/lanelet2_matching/test/lanelet2_matching_integration.cpp
  external/lanelet2_matching/test/mapping_example.osm
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/src/procedure.cpp
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/math/test_catmull_rom_spline.cpp
  simulation/traffic_simulator/test/src/math/test_hermite_curve.cpp
  simulation/traffic_simulator/test/src/test_hdmap_utils.cpp
Labels: feature

#610 Scenario simulator v2 and Autoware Architecture Proposal instruction
  docs/image/scenario_simulator_with_autoware_architecture_proposal.png
  docs/tutorials/RunWithAutowareArchitectureProposal.md
Labels: documentation

#616 remove current_action_ member variable from inherit class
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/logging_event.hpp
Labels: bug

#618 set withLaneChange parameter as false
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bug

#621 Fix/empty trafic light
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
Labels: bug
