Repository tier4/scenario_simulator_v2, pull requests merged in 2021-06, with the labels that each got.

#319 Feature/interpreter/error type
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/expression.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/arrow.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/color.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/command.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition_edge.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_dimension.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_shape.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lane_change_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/orientation.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_modify_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_set_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/pedestrian_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/priority.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reference_context.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_world_position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/route_strategy.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_target_value_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/triggering_entities_rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/world_position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_state.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/arrow.cpp
  openscenario/openscenario_interpreter/src/syntax/command.cpp
  openscenario/openscenario_interpreter/src/syntax/condition_edge.cpp
  openscenario/openscenario_interpreter/src/syntax/dynamics_dimension.cpp
  openscenario/openscenario_interpreter/src/syntax/dynamics_shape.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_type.cpp
  openscenario/openscenario_interpreter/src/syntax/pedestrian_category.cpp
  openscenario/openscenario_interpreter/src/syntax/priority.cpp
  openscenario/openscenario_interpreter/src/syntax/reference_context.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_type.cpp
  openscenario/openscenario_interpreter/src/syntax/route_strategy.cpp
  openscenario/openscenario_interpreter/src/syntax/rule.cpp
  openscenario/openscenario_interpreter/src/syntax/speed_target_value_type.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_type.cpp
  openscenario/openscenario_interpreter/src/syntax/triggering_entities_rule.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle_category.cpp
Labels: refactor

#324 Feature/remove unused mock package
  .github/workflows/Build.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/launch/manual_drive_kashiwanoha.launch.py
  mock/cpp_mock_scenarios/package.xml
  mock/cpp_mock_scenarios/src/manual_drive_kashiwanoha.cpp
  mock/joy_to_vehicle_cmd/CHANGELOG.rst
  mock/joy_to_vehicle_cmd/CMakeLists.txt
  mock/joy_to_vehicle_cmd/config/joy.yaml
  mock/joy_to_vehicle_cmd/include/joy_to_vehicle_cmd/joy_to_vehicle_cmd_component.hpp
  mock/joy_to_vehicle_cmd/launch/joy_to_vehicle_cmd.launch.py
  mock/joy_to_vehicle_cmd/package.xml
  mock/joy_to_vehicle_cmd/src/joy_to_vehicle_cmd_component.cpp
  mock/joy_to_vehicle_cmd/src/joy_to_vehicle_cmd_node.cpp
  mock/scenario_runner_mock/CHANGELOG.rst
  mock/scenario_runner_mock/CMakeLists.txt
  mock/scenario_runner_mock/README.md
  mock/scenario_runner_mock/package.xml
  mock/scenario_runner_mock/src/scenario_runner_mock.cpp
Labels: refactor

#329 fix frame logic
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/lidar_sensor.cpp
Labels: bug

#333 Feature/interpreter/release notes
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
Labels: documentation

#334 Fix typos and grammars in docs and comments
  docs/ReleaseNotes.md
  docs/design/About.md
  docs/design/AutowareAPI.md
  docs/design/OpenSCENARIOSupport.md
  docs/design/SystemArchitecture.md
  docs/design/Tier4ScenarioFormatVersion2.md
  docs/design/TrafficSimulator.md
  docs/design/ZeroMQ.md
  docs/design/uml/sequence.pu
  docs/design/uml/whole_architecture.pu
  docs/package/openscenario_interpreter/Doxyfile
  docs/tutorials/BuildInstructions.md
  docs/tutorials/RunWithDocker.md
  docs/tutorials/SimpleDemo.md
  docs/user_guide/scenario_editor/CreateSimpleScenario.md
  docs/user_guide/scenario_editor/EditExistingScenario.md
  mock/cpp_mock_scenarios/package.xml
  openscenario/openscenario_interpreter/README.md
  openscenario/openscenario_interpreter/example/lane_change.xosc
  openscenario/openscenario_interpreter/include/openscenario_interpreter/console/escape_sequence.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition_edge.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dimensions.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_add_value_rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_multiply_by_value_rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/priority.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/route_strategy.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/test/test_syntax.cpp
  openscenario/openscenario_visualization/include/openscenario_visualization/openscenario_visualization_component.hpp
  simulation/simple_sensor_simulator/README.md
  simulation/simple_sensor_simulator/package.xml
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/builtin_interfaces.proto
  simulation/simulation_interface/proto/geometry_msgs.proto
  simulation/simulation_interface/proto/openscenario_msgs.proto
  simulation/simulation_interface/proto/rosgraph_msgs.proto
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/resource/pedestrian_entity_behavior.xml
  simulation/traffic_simulator/src/behavior/pedestrian/walk_straight_action.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/metrics/momentary_stop_metric.cpp
  simulation/traffic_simulator/src/moc/catmull_rom_visualization.cpp
  simulation/traffic_simulator/src/simulation_clock/simulation_clock.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  test_runner/scenario_test_runner/README.md
  test_runner/scenario_test_runner/package.xml
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
Labels: bug

#336 Feature/speed up npc logic
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/behavior/action_node.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/vehicle_action_node.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/cache.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/traffic_simulator/src/behavior/vehicle/vehicle_action_node.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/test_math.cpp
Labels: refactor

#338 Feature/interpreter/vehicle description
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: feature

#341 Fix/traffic simulator/vehicle description
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bug

#343 Fix/traffic simulator/vehicle parameter
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: bug

#345 Fix/traffic simulator/simulation model
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#351 Fix/traffic simulator/simulation model 2
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bug

#355 Feature/get vehicle cmd
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: feature

#361 Execution timer
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/execution_timer.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
Labels: feature

#320 Relative target speed
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/absolute_target_speed.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_route_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/global_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/infrastructure_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init_actions.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lane_change_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lateral_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/longitudinal_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/private.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/private_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_target_speed.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/routing_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action_target.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_action.hpp
  openscenario/openscenario_interpreter/src/syntax/speed_target_value_type.cpp
  test_runner/scenario_test_runner/test/scenario/relative_target_speed.yaml
Labels: feature

#362 Feature/interpreter/scope
  openscenario/openscenario_interpreter/include/openscenario_interpreter/expression.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_route_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lane_change_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_modify_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_set_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/pedestrian.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/route.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_accomplished.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_current_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_evaluate.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_start.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_stream_output_operator.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_not_nothrow_default_constructible.hpp
Labels: refactor

#357 Feature/send ego command
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/visualization/visualization.hpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_client.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/autoware_control_msgs.proto
  simulation/simulation_interface/proto/autoware_vehicle_msgs.proto
  simulation/simulation_interface/proto/builtin_interfaces.proto
  simulation/simulation_interface/proto/geometry_msgs.proto
  simulation/simulation_interface/proto/openscenario_msgs.proto
  simulation/simulation_interface/proto/rosgraph_msgs.proto
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/proto/std_msgs.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#371 Feature/interpreter/documentation
  docs/design/ErrorCategories.md
  docs/design/TierIVScenarioFormatVersion2.md
  mkdocs.yml
Labels: documentation

#374 update Release note
  docs/ReleaseNotes.md
Labels: release

#378 Feature/ego entity/acquire position action
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/by_value_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/simulation_time_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_value_condition.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/test/scenario/RoutingAction.AcquirePositionAction.yaml
Labels: feature
