Repository tier4/scenario_simulator_v2, pull requests merged in 2021-10, with the labels that each got.

#540 add new section
  docs/design/About.md
  docs/design/VehicleDynamics.md
  mkdocs.yml
Labels: documentation

#542 Feature/deploy doc
  .github/workflows/Documentation.yaml
  README.md
Labels: documentation

#544 Feature/remove none status
  .github/workflows/Build.yaml
  common/simple_junit/test/src/test.cpp
  docs/ReleaseNotes.md
  docs/design/TrafficSimulator.md
  mock/cpp_mock_scenarios/package.xml
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/measurement/get_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  mock/cpp_mock_scenarios/src/metrics/momentary_stop.cpp
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  mock/cpp_mock_scenarios/src/metrics/reaction_time.cpp
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/metrics/collision_metric.cpp
  simulation/traffic_simulator/src/metrics/momentary_stop_metric.cpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
  simulation/traffic_simulator/src/metrics/traveled_distance_metric.cpp
  simulation/traffic_simulator/test/src/entity/test_vehicle_entity.cpp
  test_runner/scenario_test_runner/launch/replay_bag.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: refactor, cleanup

#545 update Release Note
  docs/ReleaseNotes.md
Labels: release, release note

#548 Fix SIGABRT due to accessing uninitialized optional
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
Labels: bug

#549 Fix/traffic simulator/autoware
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: bug

#550 update Release note for version 0.5.3
  docs/ReleaseNotes.md
Labels: release, release note

#553 Add Tier IV extension `conditionEdge="sticky"` to `1.1.xsd`
  docs/ReleaseNotes.md
  openscenario/openscenario_utility/openscenario_utility/resources/OpenSCENARIO-1.1.xsd
Labels: bug

#563 update release note for 0.5.5 release
  docs/ReleaseNotes.md
Labels: release, release note

#570 Feature/cleanup logger
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/logging_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/reset_request_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/transition_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/transition_events.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/pedestrian/behavior_tree.cpp
  simulation/behavior_tree_plugin/src/transition_events/logging_event.cpp
  simulation/behavior_tree_plugin/src/transition_events/reset_request_event.cpp
  simulation/behavior_tree_plugin/src/transition_events/transition_event.cpp
  simulation/behavior_tree_plugin/src/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: cleanup

#573 Feature/behavior debug marker
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature
