Repository tier4/scenario_simulator_v2, pull requests merged in 2021-05, with the labels that each got.

#292 use ros-setup action
  .github/workflows/Build.yaml
  .github/workflows/Documentation.yaml
  .github/workflows/NotifyFailure.yaml
  .github/workflows/ScenarioTest.yaml
  README.md
  dependency.repos
  external/concealer/package.xml
  external/junit_exporter/package.xml
  external/lanelet2_extension_psim/package.xml
  install_depends.sh
  map/kashiwanoha_map/package.xml
  mock/cpp_mock_scenarios/launch/idiot_npc.launch.py
  mock/cpp_mock_scenarios/launch/manual_drive_kashiwanoha.launch.py
  mock/cpp_mock_scenarios/launch/view_kashiwanoha.launch.py
  mock/cpp_mock_scenarios/package.xml
  mock/joy_to_vehicle_cmd/launch/joy_to_vehicle_cmd.launch.py
  mock/joy_to_vehicle_cmd/package.xml
  mock/scenario_runner_mock/package.xml
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_msgs/package.xml
  openscenario/openscenario_utility/setup.py
  openscenario/openscenario_visualization/package.xml
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/launch/example.launch.py
  simulation/simulation_interface/package.xml
  simulation/traffic_simulator/launch/mock_test.launch.py
  simulation/traffic_simulator/launch/spline_viz.launch.py
  simulation/traffic_simulator/package.xml
  test_runner/scenario_test_runner/launch/dummy_runner.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/package.xml
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/result_checker.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/scenario_test_runner/workflow.py
  test_runner/scenario_test_runner/setup.py
  test_runner/scenario_test_runner/test/test_flake8.py
Labels: feature

#294 Feature/support autoware.iv 0.11.2
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#300 add Release note
  docs/ReleaseNotes.md
  mkdocs.yml
Labels: documentation

#297 Feature/error handling
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/task_queue.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/posix/fork_exec.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/add_entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/simulation_time_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/verbose.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#302 Feature/error handling 2
  external/concealer/include/concealer/autoware.hpp
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#303 Feature/common exception package
  common/scenario_simulator_exception/CMakeLists.txt
  common/scenario_simulator_exception/include/scenario_simulator_exception/concatenate.hpp
  common/scenario_simulator_exception/include/scenario_simulator_exception/exception.hpp
  common/scenario_simulator_exception/include/scenario_simulator_exception/fold.hpp
  common/scenario_simulator_exception/package.xml
  common/scenario_simulator_exception/src/scenario_simulator_exception.cpp
  external/concealer/include/concealer/fundamental_api.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/package.xml
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/package.xml
Labels: feature

#304 Feature/synchronize clock
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/builtin_interfaces.proto
  simulation/simulation_interface/proto/rosgraph_msgs.proto
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: feature

#305 Refactor/scenario test runner
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/launch/autoware.launch.xml
  test_runner/scenario_test_runner/launch/dummy_runner.launch.py
  test_runner/scenario_test_runner/launch/simple_planning_simulator.launch.xml
  test_runner/scenario_test_runner/launch/vehicle.launch.xml
  test_runner/scenario_test_runner/launch/vehicle_interface.launch.xml
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: refactor

#307 Feature/rosbag record
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/launch.hpp
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
Labels: feature

#308 Feature/check rosbag output
  test_runner/scenario_test_runner/scenario_test_runner/result_checker.py
Labels: feature

#310 add testcase for scenario_simulator_exception package
  .github/workflows/Build.yaml
Labels: feature

#309 Fix/interpreter/deactivation
  .github/workflows/Build.yaml
  common/simple_junit/CHANGELOG.rst
  common/simple_junit/CMakeLists.txt
  common/simple_junit/include/simple_junit/test_case.hpp
  common/simple_junit/include/simple_junit/test_result.hpp
  common/simple_junit/include/simple_junit/test_suite.hpp
  common/simple_junit/include/simple_junit/test_suites.hpp
  common/simple_junit/package.xml
  common/simple_junit/src/test_suites.cpp
  external/junit_exporter/include/junit_exporter/junit_exporter.hpp
  external/junit_exporter/include/junit_exporter/test_suites.hpp
  external/junit_exporter/src/junit_exporter.cpp
  external/junit_exporter/src/test_suites.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/visibility.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/test/scenario/empty.yaml
Labels: bug, refactor

#311 change header frame id
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/lidar_sensor.cpp
Labels: feature

#312 Fix/interpreter/acquire position action
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
Labels: bug

#313 Fix/publish npc detection result in map frame
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
Labels: bug

#315 enable use raw ros timestamp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  simulation/traffic_simulator/include/traffic_simulator/simulation_clock/simulation_clock.hpp
  simulation/traffic_simulator/src/simulation_clock/simulation_clock.cpp
Labels: feature

#316 Fix/hold stream
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics_manager.hpp
  simulation/traffic_simulator/src/metrics/metrics_manager.cpp
Labels: bug

#317 Fix/interpreter/priority
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/priority.hpp
Labels: bug
