Repository tier4/scenario_simulator_v2, pull requests merged in 2021-12, with the labels that each got.

#623 Traffic lights to stop line lookup fix
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bug

#625 Fix/ci
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/behavior_tree_plugin/src/transition_events/transition_event.cpp
Labels: bug

#624 remove hard coded parameters in behavior tree plugin and use accelear…
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/vehicle_action_node.cpp
Labels: bug

#626 Feature/get driver model
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#627 Doc/behavior plugin
  docs/design/About.md
  docs/design/BehaviorPlugin.md
  docs/design/NPCBehavior.md
  docs/package/About.md
  docs/package/openscenario_interpreter/config.json
  docs/package/openscenario_visualization/config.json
  docs/package/simple_sensor_simulator/config.json
  docs/package/simulation_interface/config.json
  docs/package/traffic_simulator/config.json
  mkdocs.yml
Labels: bug, documentation

#619 AJD-254 - Random test runner
  .github/workflows/BuildIsolate.yaml
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  scenario_simulator_v2/package.xml
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/random_test_runner/CMakeLists.txt
  test_runner/random_test_runner/Readme.md
  test_runner/random_test_runner/include/random_test_runner/data_types.hpp
  test_runner/random_test_runner/include/random_test_runner/file_interactions/junit_xml_reporter.hpp
  test_runner/random_test_runner/include/random_test_runner/file_interactions/yaml_test_params_saver.hpp
  test_runner/random_test_runner/include/random_test_runner/lanelet_utils.hpp
  test_runner/random_test_runner/include/random_test_runner/metrics/almost_standstill_metric.hpp
  test_runner/random_test_runner/include/random_test_runner/metrics/ego_collision_metric.hpp
  test_runner/random_test_runner/include/random_test_runner/metrics/goal_reached_metric.hpp
  test_runner/random_test_runner/include/random_test_runner/random_test_runner.hpp
  test_runner/random_test_runner/include/random_test_runner/randomizers.hpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
  test_runner/random_test_runner/include/random_test_runner/test_randomizer.hpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/package.xml
  test_runner/random_test_runner/param/test.param.yaml
  test_runner/random_test_runner/rviz/random_test.rviz
  test_runner/random_test_runner/src/lanelet_utils.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/random_test_runner_node.cpp
  test_runner/random_test_runner/src/test_executor.cpp
  test_runner/random_test_runner/src/test_randomizer.cpp
Labels: feature

#631 disable throw errors while calling setDriverModel error
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: bug

#632 update ReleaeNotes
  docs/ReleaseNotes.md
Labels: release note

#634 update Release Note
  docs/ReleaseNotes.md
Labels: release, release note

#633 Feature/transform point
  simulation/traffic_simulator/include/traffic_simulator/math/bounding_box.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/transfrom.hpp
  simulation/traffic_simulator/src/math/bounding_box.cpp
  simulation/traffic_simulator/src/math/transform.cpp
Labels: feature, small feature

#637 Feature/pass goal poses to the plugin
  docs/design/BehaviorPlugin.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
  simulation/traffic_simulator/src/behavior/route_planner.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#639 Fix url for git clone
  docs/tutorials/BuildInstructions.md
Labels: bug, documentation

#643 update Release Note
  docs/ReleaseNotes.md
Labels: release, release note

#641 Feature/interpreter/expr
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/evaluate.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/variant.hpp
  openscenario/openscenario_interpreter/src/evaluate.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/rule.cpp
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
Labels: feature

#628 Avoid overwrite acceleration and deceleration.
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/object_controller.hpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#646 Feature/set acceleration deceleration
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: feature

#647 Support Autoware.Universe (tier4/universe)
  dependency_foxy.repos
  dependency_galactic.repos
  external/concealer/include/concealer/autoware_architecture_proposal.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/package.xml
  simulation/simulation_interface/package.xml
Labels: dependency

#649 Fix/interpreter/controller
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/properties.hpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/properties.cpp
Labels: bug

#651 update .gitignore
  .gitignore
Labels: cleanup

#650 enable call getDriverModel function in pedestrian entity.
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: bug

#653 set default driver model in pedestrian entity class
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
Labels: backward compatibility

#648 Feature/request speed change
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/speed_planning/CMakeLists.txt
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/data_types.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
Labels: feature

#652 Feature/traffic simulator/vehicle model
  .github/workflows/Build.yaml
  docs/ReleaseNotes.md
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_delay_steer_acc.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_delay_steer_acc_geared.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_ideal.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_ideal_steer_acc.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_ideal_steer_vel.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_interface.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_delay_steer_acc.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_delay_steer_acc_geared.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_ideal.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_ideal_steer_acc.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_ideal_steer_vel.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_interface.cpp
Labels: feature
