Repository tier4/scenario_simulator_v2, pull requests merged in 2021-07, with the labels that each got.

#380 Feature/misc object
  docs/ReleaseNotes.md
  docs/design/ZeroMQ.md
  openscenario/openscenario_msgs/CMakeLists.txt
  openscenario/openscenario_msgs/msg/EntityType.msg
  openscenario/openscenario_msgs/msg/MiscObjectParameters.msg
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/openscenario_msgs.proto
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/src/example.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
Labels: feature

#377 Traffic signal actions
  openscenario/openscenario_interpreter/include/openscenario_interpreter/iterator/circular_iterator.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/arrow.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/color.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/infrastructure_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/circular_check.hpp
  openscenario/openscenario_interpreter/src/syntax/arrow.cpp
  openscenario/openscenario_interpreter/src/syntax/color.cpp
  test_runner/scenario_test_runner/test/scenario/TrafficSignalControllerAction.yaml
  test_runner/scenario_test_runner/test/scenario/TrafficSignals.yaml
Labels: feature

#384 Feature/interpreter/assign route action with world position
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lane_position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/world_position.hpp
  openscenario/openscenario_interpreter/src/procedure.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
Labels: feature

#385 Remove dependency for only Autoware.Auto (to fix rosdep error)
  test_runner/scenario_test_runner/package.xml
Labels: dependencies

#388 delete OpenSCENARIOInterpreter.md
  mkdocs.yml
Labels: bug

#386 Feature/interpreter/misc object
  .github/workflows/ScenarioTest.yaml
  docs/user_guide/scenario_test_runner/ScenarioTestRunner.md
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/misc_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/misc_object_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/overload.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/syntax/collision_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/misc_object_category.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/README.md
  test_runner/scenario_test_runner/config/scenario_simulator_v2.rviz
  test_runner/scenario_test_runner/launch/replay_bag.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/setup.py
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
Labels: feature

#391 Feature/prepare 0.3.0
  docs/ReleaseNotes.md
Labels: release

#394 add credit
  docs/ReleaseNotes.md
Labels: release

#390 Feature/interpreter/traffic signal controller condition
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/arrow.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/by_value_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/color.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/src/syntax/arrow.cpp
  openscenario/openscenario_interpreter/src/syntax/color.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_phase.hpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
Labels: feature

#397 Fix/interpreter/acquire position action
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_route_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/collision_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/lane_change_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_world_position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state_action.hpp
Labels: feature

#399 change python version in documentation action
  .github/workflows/Documentation.yaml
Labels: bug, small problem

#401 Fix/typo
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
Labels: small problem

#400 remove action_status from entity
  simulation/traffic_simulator/include/traffic_simulator/behavior/pedestrian/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/pedestrian/behavior_tree.cpp
  simulation/traffic_simulator/src/behavior/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: refactor

#403 Feature/target speed planner
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/behavior/target_speed_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/target_speed_planner.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: refactor

#402 Feature/interpreter/logic file
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/define_macro.hpp
  external/concealer/src/autoware.cpp
  mock/cpp_mock_scenarios/src/idiot_npc.cpp
  mock/cpp_mock_scenarios/src/view_kashiwanoha.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/road_network.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/metrics/metrics_manager.cpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: refactor

#407 Feature/galactic support
  .github/workflows/Build.yaml
  .github/workflows/ScenarioTest.yaml
  .gitignore
  Dockerfile
  docs/ReleaseNotes.md
  docs/tutorials/BuildInstructions.md
  external/concealer/include/concealer/execute.hpp
  external/concealer/include/concealer/launch.hpp
  external/concealer/src/execute.cpp
  install_depends.sh
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/behavior/target_speed_planner.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: feature

#413 update Release Note
  docs/ReleaseNotes.md
Labels: release

#415 Release 0.4.0
  common/scenario_simulator_exception/CHANGELOG.rst
  common/scenario_simulator_exception/package.xml
  common/simple_junit/CHANGELOG.rst
  common/simple_junit/package.xml
  external/concealer/CHANGELOG.rst
  external/concealer/package.xml
  external/lanelet2_extension_psim/CHANGELOG.rst
  external/lanelet2_extension_psim/package.xml
  map/kashiwanoha_map/CHANGELOG.rst
  map/kashiwanoha_map/package.xml
  mock/cpp_mock_scenarios/CHANGELOG.rst
  mock/cpp_mock_scenarios/package.xml
  openscenario/openscenario_interpreter/CHANGELOG.rst
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter_msgs/CHANGELOG.rst
  openscenario/openscenario_interpreter_msgs/package.xml
  openscenario/openscenario_msgs/CHANGELOG.rst
  openscenario/openscenario_msgs/package.xml
  openscenario/openscenario_utility/CHANGELOG.rst
  openscenario/openscenario_utility/package.xml
  openscenario/openscenario_visualization/CHANGELOG.rst
  openscenario/openscenario_visualization/package.xml
  scenario_simulator_v2/CHANGELOG.rst
  scenario_simulator_v2/package.xml
  simulation/simple_sensor_simulator/CHANGELOG.rst
  simulation/simple_sensor_simulator/package.xml
  simulation/simulation_interface/CHANGELOG.rst
  simulation/simulation_interface/package.xml
  simulation/traffic_simulator/CHANGELOG.rst
  simulation/traffic_simulator/package.xml
  test_runner/scenario_test_runner/CHANGELOG.rst
  test_runner/scenario_test_runner/package.xml
Labels: release

#416 add CheckAndComment action
  .github/workflows/CheckAndCommentAction.yaml
Labels: feature

#409 Feature/autoware/pose with covariance
  docs/ReleaseNotes.md
  external/concealer/include/concealer/miscellaneous_api.hpp
  external/concealer/src/autoware.cpp
  openscenario/openscenario_interpreter/CMakeLists.txt
Labels: feature

#417 Feature/add mock scenarios
  .github/workflows/ScenarioTest.yaml
  mock/cpp_mock_scenarios/launch/idiot_npc.launch.py
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/src/idiot_npc.cpp
  openscenario/openscenario_utility/setup.py
  test_runner/scenario_test_runner/launch/replay_bag.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/workflow.py
  test_runner/scenario_test_runner/setup.py
Labels: feature

#419 Feature/rename moc to mock
  docs/tutorials/RunWithDocker.md
  docs/tutorials/SimpleDemo.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/catalogs.hpp
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/idiot_npc.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/config/moc_test.rviz
  simulation/traffic_simulator/config/spline_viz.rviz
  simulation/traffic_simulator/launch/mock_test.launch.py
  simulation/traffic_simulator/launch/spline_viz.launch.py
  simulation/traffic_simulator/src/moc/catmull_rom_visualization.cpp
  simulation/traffic_simulator/src/moc/scenario_runner_moc_node.cpp
Labels: small problem

#421 Fix/npc target speed in follow front entity action
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/behavior/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
Labels: bug

#425 Fix/add include crosswalk option
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/behavior/pedestrian/follow_lane_action.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bug

#426 update Release note
  docs/ReleaseNotes.md
Labels: release
