Repository tier4/scenario_simulator_v2, pull requests merged in 2021-09, with the labels that each got.

#485 Feature/test simulation interface
  openscenario/openscenario_msgs/CMakeLists.txt
  openscenario/openscenario_msgs/msg/Property.msg
  openscenario/openscenario_msgs/msg/VehicleParameters.msg
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/src/constants.cpp
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/src/example.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/simulation_interface/test/expect_equal_macros.hpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
Labels: test

#487 Feature/get longituninal distance behind
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/measurement/CMakeLists.txt
  mock/cpp_mock_scenarios/src/measurement/get_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: feature

#488 update ReleaseNote.md
  docs/ReleaseNotes.md
Labels: release note

#489 Feature/test traffic light
  simulation/traffic_simulator/test/CMakeLists.txt
  simulation/traffic_simulator/test/map/lanelet2_map.osm
  simulation/traffic_simulator/test/src/traffic_lights/CMakeLists.txt
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_state.cpp
Labels: test

#490 Fix/scenario object scope
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entities.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
  test_runner/scenario_test_runner/test/scenario/duplicated-parameter.yaml
Labels: bug

#492 Feature/add traffic light test
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_phase.hpp
  simulation/traffic_simulator/test/src/expect_eq_macros.hpp
  simulation/traffic_simulator/test/src/traffic_lights/CMakeLists.txt
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
Labels: bug, test

#493 Fix/dependency
  .github/workflows/ScenarioTest.yaml
  Dockerfile
  dependency_foxy.repos
  dependency_galactic.repos
  docs/ReleaseNotes.md
  install_depends.sh
Labels: dependency

#496 Fix/update repos files
  .gitignore
  Dockerfile
  dependency_foxy.repos
  dependency_galactic.repos
  docs/ReleaseNotes.md
  docs/tutorials/BuildInstructions.md
  install_depends.sh
Labels: dependency

#497 remove unused steps
  .github/workflows/Docker.yaml
  .github/workflows/Documentation.yaml
  .github/workflows/NotifyFailure.yaml
  .github/workflows/ScenarioTest.yaml
Labels: feature

#498 Feature/remove unused codes in entity
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/catalogs.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/pedestrian/follow_lane_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/pedestrian/pedestrian_action_node.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/pedestrian/walk_straight_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/lane_change_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/vehicle/vehicle_action_node.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_parameter.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_parameter.hpp
  simulation/traffic_simulator/src/behavior/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: refactor

#486 Set name in the proto request for non-ego vehicles
  simulation/traffic_simulator/src/api/api.cpp
Labels: refactor

#458 Add arrow markers to visualize goal poses of entities
  docs/ReleaseNotes.md
  openscenario/openscenario_msgs/msg/EntityStatusWithTrajectory.msg
  openscenario/openscenario_visualization/include/openscenario_visualization/openscenario_visualization_component.hpp
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/route_planner.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: feature

#499 update Relase Note
  docs/ReleaseNotes.md
Labels: release note

#500 Fix/offset calculation
  docs/ReleaseNotes.md
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/math/linear_algebra.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/linear_algebra.cpp
  simulation/traffic_simulator/test/src/expect_eq_macros.hpp
  simulation/traffic_simulator/test/src/math/CMakeLists.txt
  simulation/traffic_simulator/test/src/math/test_linear_algebra.cpp
Labels: bug

#503 Feature/cleanup code
  .github/workflows/Build.yaml
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  docs/design/AutowareAPI.md
  docs/design/Metrics.md
  docs/design/uml/sequence.pu
  docs/image/what_is_scenario_testing_framework.drawio
  docs/user_guide/scenario_test_runner/HowToWriteWorkflowFile.md
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/autoware_traffic_light.hpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/rviz/mock_test.rviz
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  openscenario/openscenario_interpreter/config/default.rviz
  openscenario/openscenario_interpreter/example/lane_change.xosc
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition_edge.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/test/example.xosc
  openscenario/openscenario_interpreter/test/test_syntax.cpp
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/simple_sensor_simulator/config/scenario_simulator.rviz
  simulation/simulation_interface/include/simulation_interface/zmq_client.hpp
  simulation/simulation_interface/proto/autoware_vehicle_msgs.proto
  simulation/simulation_interface/proto/openscenario_msgs.proto
  simulation/simulation_interface/proto/std_msgs.proto
  simulation/traffic_simulator/CHANGELOG.rst
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/cache.hpp
  simulation/traffic_simulator/src/behavior/action_node.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/test/catalog/VehicleCatalog.xosc
  simulation/traffic_simulator/test/src/math/CMakeLists.txt
  simulation/traffic_simulator/test/src/math/test_bounding_box.cpp
  simulation/traffic_simulator/test/src/math/test_polynomial_solver.cpp
  simulation/traffic_simulator/test/src/math/test_uuid.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_state.cpp
  test_runner/scenario_test_runner/config/scenario_simulator_v2.rviz
  test_runner/scenario_test_runner/test/scenario/ControllerAction.AssignControllerAction.yaml
  test_runner/scenario_test_runner/test/scenario/RoutingAction.AcquirePositionAction.yaml
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
  test_runner/scenario_test_runner/test/scenario/failure.yaml
  test_runner/scenario_test_runner/test/scenario/simple.xosc
  test_runner/scenario_test_runner/test/scenario/success.yaml
Labels: bug, cleanup

#504 Fix/dockerfile
  Dockerfile
Labels: bug

#508 update release note
  docs/ReleaseNotes.md
Labels: release note

#515 update docs
  docs/design/Metrics.md
Labels: documentation

#516 Fix the argument of `zmqpp::poller::poll()`
  simulation/simulation_interface/src/zmq_multi_server.cpp
Labels: bug

#518 Feature/add testcase for simple junit
  common/simple_junit/test/expected/attributes.junit.xml
  common/simple_junit/test/expected/complex.junit.xml
  common/simple_junit/test/expected/error.junit.xml
  common/simple_junit/test/expected/failure.junit.xml
  common/simple_junit/test/expected/pass.junit.xml
  common/simple_junit/test/expected/testsuites_name.junit.xml
  common/simple_junit/test/src/test.cpp
Labels: test

#506 Feature/Interpreter/add entity action
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/add_entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/delete_entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entities.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_declaration.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/road_network.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signals.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/test/scenario/all-in-one.yaml
Labels: feature

#520 Feature/standstill metric
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  docs/design/ErrorCategories.md
  docs/design/Metrics.md
  docs/design/SimulationResultFormat.md
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/standstill_metric.hpp
  simulation/traffic_simulator/src/metrics/standstill_metric.cpp
Labels: feature

#521 Feature/collision metric
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  docs/design/Metrics.md
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/metrics/collision_metric.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics.hpp
  simulation/traffic_simulator/src/metrics/collision_metric.cpp
Labels: feature

#502 Removed cargo delivery dependency
  map/kashiwanoha_map/map/private_road_and_walkway_ele_fix/lanelet2_map.osm
  mock/cpp_mock_scenarios/package.xml
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/metrics/momentary_stop.cpp
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  mock/cpp_mock_scenarios/src/metrics/reaction_time.cpp
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
Labels: cleanup

#511 Feature/metrics get jerk from autoware
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/object_controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_object.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metric_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
Labels: feature

#526 Update Documentation.yaml
  .github/workflows/Documentation.yaml
Labels: bug

#525 rename scenario_test_runner_launch to scenario_simulator_launch
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/package.xml
Labels: refactor

#523 Refine documents and define contribution guidelines
  CONTRIBUTING.md
  docs/README.md
  docs/design/About.md
  docs/design/AutowareAPI.md
  docs/design/ErrorCategories.md
  docs/design/Metrics.md
  docs/design/SimpleSensorSimulator.md
  docs/design/SimulationResultFormat.md
  docs/design/SystemArchitecture.md
  docs/design/TierIVScenarioFormatVersion2.md
  docs/design/TrafficSimulator.md
  docs/design/ZeroMQ.md
  docs/etc/ContactUs.md
  docs/etc/DevelopmentRules.md
  docs/etc/HowToContribute.md
  mkdocs.yml
Labels: documentation

#527 change log directory cleanup behavior
  docs/ReleaseNotes.md
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: bug

#529 Feature/cpp mock scenario ament cmake
  .github/workflows/Build.yaml
  .github/workflows/ScenarioTest.yaml
  codecov.yml
  common/simple_junit/include/simple_junit/junit5.hpp
  common/simple_junit/test/expected/attributes.junit.xml
  common/simple_junit/test/expected/complex.junit.xml
  common/simple_junit/test/expected/error.junit.xml
  common/simple_junit/test/expected/failure.junit.xml
  common/simple_junit/test/expected/pass.junit.xml
  common/simple_junit/test/expected/testsuites_name.junit.xml
  common/simple_junit/test/src/test.cpp
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/cmake/add_cpp_mock_scenario_test.cmake
  mock/cpp_mock_scenarios/cpp_mock_scenarios_ament_cmake-extras.cmake
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/package.xml
  mock/cpp_mock_scenarios/src/collision/CMakeLists.txt
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/crosswalk/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_front_entity/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_lane/CMakeLists.txt
  mock/cpp_mock_scenarios/src/lane_change/CMakeLists.txt
  mock/cpp_mock_scenarios/src/measurement/CMakeLists.txt
  mock/cpp_mock_scenarios/src/merge/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  mock/cpp_mock_scenarios/src/move_backward/CMakeLists.txt
  mock/cpp_mock_scenarios/src/pedestrian/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_light/CMakeLists.txt
  openscenario/openscenario_utility/openscenario_utility/scenario_validation.py
  openscenario/openscenario_utility/setup.py
Labels: feature, cleanup

#530 Traffic lights ZMQ API
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: feature

#534 fix command
  docs/tutorials/SimpleDemo.md
Labels: documentation

#533 Feature/interpreter/distance condition
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_type.hpp
  openscenario/openscenario_interpreter/src/scope.cpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: feature

#536 Fix/get longitudinal distance
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: bug

#537 update documentation
  docs/ReleaseNotes.md
Labels: documentation, release, release note
