Repository tier4/scenario_simulator_v2, pull requests merged in 2022-07, with the labels that each got.

#801 Move non-instantaneous init actions into storyboard
  .github/workflows/custom_spell.json
  openscenario/openscenario_interpreter/include/openscenario_interpreter/expression.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/catalog_reference.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init_actions.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/private.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_stream_output_operator.hpp
  openscenario/openscenario_interpreter/src/evaluate.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/init.cpp
  openscenario/openscenario_interpreter/src/syntax/init_actions.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_add_value_rule.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_multiply_by_value_rule.cpp
  openscenario/openscenario_interpreter/src/syntax/private.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
Labels: improvement

#838 Doc/5th improvement
  docs/developer_guide/AutowareAPI.md
  docs/developer_guide/Communication.md
  docs/user_guide/ScenarioTips.md
  docs/user_guide/scenario_editor/CreateSimpleScenario.md
  docs/user_guide/scenario_editor/RelativePosition.md
  docs/user_guide/scenario_editor/ScenarioEditorUserGuide.md
  mkdocs.yml
Labels: documentation

#837 Update/rviz display
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: feature, improvement

#835 Enable raycaster hit intersect with geometries in the scene
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/raycaster.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/primitives/primitive.cpp
Labels: bug

#840 Update base image version in Documentation CI workflow
  .github/workflows/Documentation.yaml
Labels: bug, github actions

#839 Doc/6th improvement
  docs/developer_guide/OpenSCENARIOSupport.md
  docs/image/lane_change.gif
  docs/user_guide/QuickStart.md
  docs/user_guide/RunTestScenarioWithDocker.md
  docs/user_guide/RunWithDocker.md
  docs/user_guide/ScenarioTips.md
  docs/user_guide/deprected/SimpleDemo.md
  mkdocs.yml
Labels: documentation

#842 Concealer dangling reference fix
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/src/autoware.cpp
Labels: bug

#845 update documentation.yaml
  .github/workflows/Documentation.yaml
Labels: bug

#844 Feature/use GitHub registry
  .github/workflows/Docker.yaml
  README.md
  docs/README.md
  docs/ReleaseNotes.md
  docs/user_guide/RunWithDocker.md
Labels: feature

#841 Feature/cooperator
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/src/autoware_universe.cpp
Labels: improvement

#846 Refactor/interpreter/scope
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entities.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/open_scenario.hpp
  openscenario/openscenario_interpreter/src/scope.cpp
  openscenario/openscenario_interpreter/src/syntax/add_entity_action.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_location.cpp
  openscenario/openscenario_interpreter/src/syntax/collision_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/entities.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_object.cpp
  openscenario/openscenario_interpreter/src/syntax/open_scenario.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/teleport_action.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle_category.cpp
  openscenario/openscenario_interpreter/test/test_syntax.cpp
Labels: refactor
