Repository tier4/scenario_simulator_v2, pull requests merged in 2022-03, with the labels that each got.

#714 Fix/get longitudinal distance
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bug

#715 fix invalid command
  docs/tutorials/RunWithDocker.md
Labels: bug, documentation

#717 Improvement/sample scenario
  test_runner/scenario_test_runner/README.md
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/scenario/ByValueCondition.UserDefinedValueCondition.yaml
  test_runner/scenario_test_runner/scenario/ControllerAction.AssignControllerAction.yaml
  test_runner/scenario_test_runner/scenario/CustomCommandAction.FaultInjectionAction.yaml
  test_runner/scenario_test_runner/scenario/LateralAction.LaneChangeAction.yaml
  test_runner/scenario_test_runner/scenario/LongitudinalAction.SpeedAction.yaml
  test_runner/scenario_test_runner/scenario/Property.isBlind.yaml
  test_runner/scenario_test_runner/scenario/Property.maxSpeed.yaml
  test_runner/scenario_test_runner/scenario/RoutingAction.AcquirePositionAction.yaml
  test_runner/scenario_test_runner/scenario/TrafficSignalControllerAction.yaml
  test_runner/scenario_test_runner/scenario/TrafficSignals.yaml
  test_runner/scenario_test_runner/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/scenario/autoware-simple.yaml
  test_runner/scenario_test_runner/scenario/catalog/controller/all-in-one-controller.yaml
  test_runner/scenario_test_runner/scenario/catalog/maneuver/all-in-one-maneuver.yaml
  test_runner/scenario_test_runner/scenario/catalog/vehicle/all-in-one-vehicle.yaml
  test_runner/scenario_test_runner/scenario/collision.yaml
  test_runner/scenario_test_runner/scenario/distance-condition.yaml
  test_runner/scenario_test_runner/scenario/duplicated-parameter.yaml
  test_runner/scenario_test_runner/scenario/empty.yaml
  test_runner/scenario_test_runner/scenario/failure.yaml
  test_runner/scenario_test_runner/scenario/minimal.yaml
  test_runner/scenario_test_runner/scenario/parameter.yaml
  test_runner/scenario_test_runner/scenario/prefixed-name-reference.yaml
  test_runner/scenario_test_runner/scenario/relative_target_speed.yaml
  test_runner/scenario_test_runner/scenario/sample.yaml
  test_runner/scenario_test_runner/scenario/spawn_relative_world.yaml
  test_runner/scenario_test_runner/scenario/stand-still.yaml
  test_runner/scenario_test_runner/scenario/success.yaml
  test_runner/scenario_test_runner/setup.py
  test_runner/scenario_test_runner/test/scenario/Autoware.Curve.yaml
  test_runner/scenario_test_runner/test/scenario/Autoware.NPCOnTheRoad.yaml
  test_runner/scenario_test_runner/test/scenario/Autoware.Overtake.yaml
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
  test_runner/scenario_test_runner/test/scenario/minimal.yaml
  test_runner/scenario_test_runner/test/scenario/simple.xosc
Labels: test

#721 update release note
  docs/ReleaseNotes.md
Labels: documentation

#720 Refactor/interpreter/execution
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/execution_timer.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/open_scenario.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_definition.cpp
  test_runner/scenario_test_runner/scenario/minimal.yaml
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: cleanup

#711 Refactor/interpreter/storyboard element
  openscenario/openscenario_interpreter/include/openscenario_interpreter/object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/story.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trigger.hpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/actors.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_locations.cpp
  openscenario/openscenario_interpreter/src/syntax/condition_group.cpp
  openscenario/openscenario_interpreter/src/syntax/entities.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_declarations.cpp
  openscenario/openscenario_interpreter/src/syntax/private.cpp
  openscenario/openscenario_interpreter/src/syntax/properties.cpp
  openscenario/openscenario_interpreter/src/syntax/route.cpp
  openscenario/openscenario_interpreter/src/syntax/story.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signals.cpp
  openscenario/openscenario_interpreter/src/syntax/trigger.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_action.cpp
Labels: refactor

#725 Doc/release note format
  docs/ReleaseNotes.md
Labels: documentation

#726 Feature/semantics
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/catalogs.hpp
  openscenario/openscenario_interpreter/src/syntax/misc_object.cpp
  openscenario/openscenario_interpreter/src/syntax/pedestrian.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/proto/traffic_simulator_msgs.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/test/expect_equal_macros.hpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/test/src/catalogs.hpp
  simulation/traffic_simulator_msgs/CMakeLists.txt
  simulation/traffic_simulator_msgs/msg/EntityStatus.msg
  simulation/traffic_simulator_msgs/msg/EntitySubtype.msg
  simulation/traffic_simulator_msgs/msg/MiscObjectParameters.msg
  simulation/traffic_simulator_msgs/msg/PedestrianParameters.msg
  simulation/traffic_simulator_msgs/msg/VehicleParameters.msg
  test_runner/random_test_runner/src/test_executor.cpp
Labels: feature

#727 Feature/interpreter/reader
  .github/workflows/BuildIsolate.yaml
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/src/syntax/catalog.cpp
  openscenario/openscenario_interpreter_example/CMakeLists.txt
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/openscenario_interpreter_example/src/uniform_distribution.cpp
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature

#732 remove released package from repos file
  dependency_galactic.repos
Labels: dependency

#729 Feature/ignore raycast result
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
Labels: feature

#734 Fix/interpreter/global action
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/record.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/global_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_action.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/record.cpp
  openscenario/openscenario_interpreter/src/syntax/global_action.cpp
  openscenario/openscenario_interpreter/src/syntax/private.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_action.cpp
  simulation/behavior_tree_plugin/src/transition_events/logging_event.cpp
  test_runner/scenario_test_runner/scenario/failure.yaml
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: bug

#737 add Release option to the build instruction
  docs/tutorials/BuildInstructions.md
Labels: documentation

#708 Ajd 331 optimization
  docs/ReleaseNotes.md
  docs/design/BehaviorPlugin.md
  simulation/behavior_tree_plugin/config/vehicle_entity_behavior.xml
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/vehicle_action_node.hpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/lane_change_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/vehicle_action_node.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
Labels: feature

#735 Feature/interpreter/object controller
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/properties.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle.hpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_object.cpp
Labels: feature

#739 remove <<<<<<< HEAD
  docs/ReleaseNotes.md
Labels: documentation

#733 Feature/improve ego lane matching
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: feature

#742 update repos file
  dependency_galactic.repos
Labels: dependency

#743 Feature/remove operational design domains
  dependency_galactic.repos
Labels: dependency
