Repository tier4/scenario_simulator_v2, pull requests merged in 2022-04, with the labels that each got.

#744 remove functions in color_names package
  openscenario/openscenario_visualization/package.xml
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/traffic_simulator/include/traffic_simulator/color_utils/color_utils.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/color_utils/color_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: cleanup

#746 update icon
  docs/image/icon.png
Labels: documentation

#690 zmq client can connect through the network
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/src/constants.cpp
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  test_runner/random_test_runner/Readme.md
  test_runner/random_test_runner/include/random_test_runner/data_types.hpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/src/random_test_runner.cpp
Labels: feature

#747 Fix/calculate stop distance
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
Labels: bug

#749 Feature/job system
  mock/cpp_mock_scenarios/src/speed_planning/CMakeLists.txt
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/behavior/target_speed_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/job/job.hpp
  simulation/traffic_simulator/include/traffic_simulator/job/job_list.hpp
  simulation/traffic_simulator/src/behavior/target_speed_planner.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/job/job.cpp
  simulation/traffic_simulator/src/job/job_list.cpp
Labels: feature

#728 Fix/Interpreter/Interrupt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter_node.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: feature

#751 Feature/behavior request enum
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/reset_request_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/pedestrian/behavior_tree.cpp
  simulation/behavior_tree_plugin/src/pedestrian/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/pedestrian/walk_straight_action.cpp
  simulation/behavior_tree_plugin/src/transition_events/reset_request_event.cpp
  simulation/behavior_tree_plugin/src/vehicle/behavior_tree.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/data_types.hpp
  simulation/traffic_simulator/src/behavior/behavior_plugin_base.cpp
  simulation/traffic_simulator/src/data_type/data_types.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: refactor

#712 use detected objects instead of predicted ones
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: bug

#731 Feature/interpreter/category
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/misc_object_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/pedestrian_category.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle_category.hpp
  openscenario/openscenario_interpreter/src/syntax/misc_object.cpp
  openscenario/openscenario_interpreter/src/syntax/pedestrian.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle.cpp
Labels: feature

#740 Refactor/traffic simulator/traffic light manager
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_light/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/arrow.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/color.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/arrow.cpp
  openscenario/openscenario_interpreter/src/syntax/color.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state_action.cpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_phase.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_state.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_state.cpp
  simulation/traffic_simulator/test/src/traffic_lights/CMakeLists.txt
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_state.cpp
  test_runner/scenario_test_runner/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/scenario/catalog/maneuver/all-in-one-maneuver.yaml
Labels: refactor

#755 Fix/invalid timeout parameter
  docs/tutorials/RunWithDocker.md
Labels: bug, documentation

#756 Fix/docker tag
  docs/tutorials/RunTestScenarioWithDocker.md
Labels: bug, documentation

#752 Feature/reset acecel in request speed change
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  simulation/traffic_simulator/include/traffic_simulator/job/job.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: feature

#759 Feature/traffic simulator/traffic light
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
Labels: improvement

#757 Ignore terms above the second order of delta s
  docs/package/traffic_simulator/images/get_length_in_hermite_curve.png
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/expect_eq_macros.hpp
  simulation/traffic_simulator/test/src/math/test_catmull_rom_spline.cpp
Labels: feature

#761 Fix undef macro target
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
Labels: bug

#764 change image directory
  docs/package/traffic_simulator/.gitignore
  docs/package/traffic_simulator/markdown/images/get_length_in_hermite_curve.png
Labels: bug

#762 fix email address
  simulation/behavior_tree_plugin/package.xml
Labels: small problem

#769 Fix/doc
  docs/tutorials/RunTestScenarioWithDocker.md
Labels: documentation

#697 Ajd 345 random test runner with autoware universe
  test_runner/random_test_runner/CMakeLists.txt
  test_runner/random_test_runner/include/random_test_runner/data_types.hpp
  test_runner/random_test_runner/include/random_test_runner/random_test_runner.hpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/src/data_types.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: feature

#771 update Release Note
  docs/ReleaseNotes.md
Labels: release note

#760 Feature/emergency state for fault injection
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: feature
