Repository tier4/scenario_simulator_v2, pull requests merged in 2022-10, with the labels that each got.

#886 Implement parallelization into lidar simulation (embree library) [AJD-520]
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/raycaster.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/lidar_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/raycaster.cpp
Labels: feature

#892 Feature/interpreter/follow trajectory action 2
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/follow_trajectory_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/following_mode.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/none.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/polyline.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/routing_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/shape.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/time_reference.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/timing.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trajectory.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trajectory_following_mode.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trajectory_ref.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vertex.hpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/dynamics_dimension.cpp
  openscenario/openscenario_interpreter/src/syntax/follow_trajectory_action.cpp
  openscenario/openscenario_interpreter/src/syntax/following_mode.cpp
  openscenario/openscenario_interpreter/src/syntax/polyline.cpp
  openscenario/openscenario_interpreter/src/syntax/routing_action.cpp
  openscenario/openscenario_interpreter/src/syntax/shape.cpp
  openscenario/openscenario_interpreter/src/syntax/time_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/timing.cpp
  openscenario/openscenario_interpreter/src/syntax/trajectory.cpp
  openscenario/openscenario_interpreter/src/syntax/trajectory_following_mode.cpp
  openscenario/openscenario_interpreter/src/syntax/trajectory_ref.cpp
  openscenario/openscenario_interpreter/src/syntax/vertex.cpp
  openscenario/openscenario_utility/openscenario_utility/conversion.py
  openscenario/openscenario_utility/openscenario_utility/resources/OpenSCENARIO-1.2.xsd
  openscenario/openscenario_utility/openscenario_utility/scenario_validation.py
  openscenario/openscenario_utility/openscenario_utility/validation.py
  test_runner/scenario_test_runner/scenario/RoutingAction.FollowTrajectoryAction.yaml
Labels: feature

#882 Update BuildIsolate.yaml
  .github/workflows/BuildIsolate.yaml
Labels: github actions

#890 Refactor scenario_test_runner for openscenario_preprocessor
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_preprocessor.hpp
  openscenario/openscenario_interpreter/src/openscenario_preprocessor.cpp
  openscenario/openscenario_interpreter/src/openscenario_preprocessor_node.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter_msgs/CMakeLists.txt
  openscenario/openscenario_interpreter_msgs/srv/PreprocessorCheckDerivativeRemained.srv
  openscenario/openscenario_interpreter_msgs/srv/PreprocessorDerive.srv
  openscenario/openscenario_interpreter_msgs/srv/PreprocessorLoad.srv
  openscenario/openscenario_utility/openscenario_utility/validation.py
  openscenario/openscenario_utility/package.xml
  openscenario/openscenario_utility/setup.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: refactor

#893 Feature/interpreter/follow trajectory action 3
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/catalog_reference.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/src/syntax/assign_controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/assign_route_action.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_object.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
  openscenario/openscenario_interpreter/src/syntax/trajectory_ref.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/route_planner.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/metrics/momentary_stop_metric.cpp
Labels: refactor

#896 Refactor/traffic simulator/spawn
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/follow_lane/follow_with_offset.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_lateral_velocity.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_time.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_time.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  mock/cpp_mock_scenarios/src/measurement/get_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/momentary_stop.cpp
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  mock/cpp_mock_scenarios/src/metrics/reaction_time.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/syntax/add_entity_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/metrics/momentary_stop_metric.cpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
  simulation/traffic_simulator/src/metrics/traveled_distance_metric.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: improvement

#848 Concealer service clients encapsulation; velocity limit setting fix
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/include/concealer/utility/service_with_validation.h
  external/concealer/src/autoware_universe.cpp
Labels: bug

#900 Feature/traffic simulator/behavior parameter
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamic_constraints.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/performance.hpp
  openscenario/openscenario_interpreter/src/syntax/dynamic_constraints.cpp
  openscenario/openscenario_interpreter/src/syntax/performance.cpp
  openscenario/openscenario_interpreter/src/syntax/speed_profile_action.cpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator_msgs/CMakeLists.txt
  simulation/traffic_simulator_msgs/msg/BehaviorParameter.msg
  simulation/traffic_simulator_msgs/msg/DynamicConstraints.msg
  simulation/traffic_simulator_msgs/msg/Performance.msg
Labels: feature

#883 Feature/interpreter/priority
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init_actions.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/story.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_action.hpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/priority.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_definition.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_action.cpp
  test_runner/scenario_test_runner/scenario/all-in-one.yaml
Labels: feature
