Repository tier4/scenario_simulator_v2, pull requests merged in 2022-09, with the labels that each got.

#876 change action version
  .github/workflows/Documentation.yaml
Labels: bug

#823 Feature/start npc logic api
  docs/ReleaseNotes.md
  docs/developer_guide/BehaviorPlugin.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/task_queue.cpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/stop_watch.hpp
  simulation/traffic_simulator/include/traffic_simulator/simulation_clock/simulation_clock.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/simulation_clock/simulation_clock.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: feature

#875 Feature/concealer/acceleration
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#879 Update Docker.yaml
  .github/workflows/Docker.yaml
Labels: feature

#885 Add autoware_msgs to dependencies
  dependency_galactic.repos
  dependency_humble.repos
Labels: github actions

#891 Feature/interpreter/follow trajectory action
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_dimension.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_shape.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_target_lane.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_target_value_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/transition_dynamics.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/reset_request_event.hpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/behavior.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/data_types.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/lane_change.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/speed_change.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/data_type/behavior.cpp
  simulation/traffic_simulator/src/data_type/data_types.cpp
  simulation/traffic_simulator/src/data_type/lane_change.cpp
  simulation/traffic_simulator/src/data_type/speed_change.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: feature
