Repository tier4/scenario_simulator_v2, pull requests merged in 2022-05, with the labels that each got.

#710 Ajd 331 optimization 2nd stage
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/vehicle_action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline_interface.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_subspline.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/catmull_rom_subspline.cpp
Labels: improvement

#784 Doc: Update OpenSCENARIO support status
  .github/workflows/Documentation.yaml
  docs/design/OpenSCENARIOSupport.md
Labels: documentation

#785 Doc/improve
  .github/workflows/Documentation.yaml
  .github/workflows/DocumentationLinkCheck.yaml
  .textlintrc
  docs/README.md
  docs/ReleaseNotes.md
  docs/design/About.md
  docs/design/AutowareAPI.md
  docs/design/BehaviorPlugin.md
  docs/design/Metrics.md
  docs/design/NPCBehavior.md
  docs/design/SimpleSensorSimulator.md
  docs/design/SimulationResultFormat.md
  docs/design/SystemArchitecture.md
  docs/design/TierIVScenarioFormatVersion2.md
  docs/design/TrafficSimulator.md
  docs/design/ZeroMQ.md
  docs/etc/ContactUs.md
  docs/etc/HowToContribute.md
  docs/package/About.md
  docs/package/simple_sensor_simulator/config.json
  docs/tutorials/RunWithAutowareUniverse.md
  docs/tutorials/RunWithDocker.md
  docs/tutorials/SimpleDemo.md
  docs/user_guide/scenario_editor/CreateSimpleScenario.md
  docs/user_guide/scenario_editor/EditExistingScenario.md
  docs/user_guide/scenario_editor/RelativePosition.md
  docs/user_guide/scenario_test_runner/HowToWriteWorkflowFile.md
  docs/user_guide/scenario_test_runner/ScenarioTestRunner.md
  external/lanelet2_extension_psim/docs/lanelet2_format_extension.md
  external/lanelet2_matching/README.md
  mkdocs.yml
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state_action.hpp
  openscenario/openscenario_visualization/README.md
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline_interface.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_subspline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metric_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_module_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_sink.hpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/catmull_rom_subspline.cpp
  simulation/traffic_simulator/src/math/distance.cpp
  simulation/traffic_simulator/src/metrics/metric_base.cpp
  simulation/traffic_simulator/src/metrics/metrics_manager.cpp
  simulation/traffic_simulator/src/traffic/traffic_controller.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
  test_runner/random_test_runner/Readme.md
  test_runner/scenario_test_runner/README.md
Labels: documentation, cleanup, improvement, github actions

#758 Feature/interpreter/instantaneously transition
  .github/workflows/Documentation.yaml
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element_state_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/execution_timer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/pair.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_definition.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state_condition.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: improvement

#792 Fix/autoware/reverse gear
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/src/autoware_universe.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: bug
