Repository tier4/scenario_simulator_v2, pull requests merged in 2022-12, with the labels that each got.

#928 Feature/interpreter/speed profile action
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_profile_action.hpp
  openscenario/openscenario_interpreter/src/syntax/speed_profile_action.cpp
  test_runner/scenario_test_runner/scenario/LongitudinalAction.SpeedProfileAction.yaml
Labels: feature

#922 Precompute rotation matrix
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/raycaster.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/lidar_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/raycaster.cpp
Labels: wait for regression test

#935 add --include-eol-distros
  .github/workflows/ScenarioTest.yaml
Labels: bug

#941 feat(ci): add InterfaceUpdateNotification.yaml
  .github/workflows/Documentation.yaml
  .github/workflows/InterfaceUpdateNotification.yaml
Labels: github actions

#933 delete metric when the entity was despawned
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
Labels: wait for regression test
