Repository tier4/scenario_simulator_v2, pull requests merged in 2022-02, with the labels that each got.

#689 feat(behavior_velocity): add occlusion spot no stopping area marker
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
Labels: feature, small feature

#686 Fix/warp problem
  docs/ReleaseNotes.md
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/hermite_curve.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/linear_algebra.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/src/math/linear_algebra.cpp
Labels: bug

#688 Fix/traffic simulator/traffic light manager
  openscenario/openscenario_interpreter/src/syntax/phase.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_controller.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_state.cpp
  simulation/traffic_simulator/test/src/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
Labels: bug

#692 Refactor/interpreter/storyboard element
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/acquire_position_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/assign_route_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_modify_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_set_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/teleport_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_controller_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state_action.hpp
  openscenario/openscenario_interpreter/src/syntax/acquire_position_action.cpp
  openscenario/openscenario_interpreter/src/syntax/assign_route_action.cpp
  openscenario/openscenario_interpreter/src/syntax/controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_action.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_modify_action.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_set_action.cpp
  openscenario/openscenario_interpreter/src/syntax/teleport_action.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state_action.cpp
Labels: refactor

#693 Refactor/interpreter/storyboard element state
  openscenario/openscenario_interpreter/include/openscenario_interpreter/expression.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/has_member_function_current_state.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/if_has_member_function_current_state.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/story.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state_condition.cpp
Labels: refactor

#663 Dependency/remove architecture proposal
  .gitignore
  dependency_foxy.repos
  dependency_galactic.repos
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_architecture_proposal.hpp
  external/concealer/include/concealer/autoware_auto.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/conversion.hpp
  external/concealer/package.xml
  external/concealer/src/autoware_architecture_proposal.cpp
  external/concealer/src/autoware_auto.cpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/custom_command_action.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
  openscenario/user_defined_value_condition_example/package.xml
  openscenario/user_defined_value_condition_example/src/timeout.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/autoware_auto_control_msgs.proto
  simulation/simulation_interface/proto/autoware_auto_vehicle_msgs.proto
  simulation/simulation_interface/proto/autoware_control_msgs.proto
  simulation/simulation_interface/proto/autoware_vehicle_msgs.proto
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/proto/traffic_simulator_msgs.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/test/expect_equal_macros.hpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_state.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_state.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_state.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: dependency

#696 Dependency/remove autoware auto
  .github/workflows/Build.yaml
  .github/workflows/BuildIsolate.yaml
  .github/workflows/Docker.yaml
  .github/workflows/ScenarioTest.yaml
  dependency_foxy.repos
  docs/ReleaseNotes.md
  docs/tutorials/BuildInstructions.md
  docs/tutorials/RunWithDocker.md
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware_auto.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/package.xml
  external/concealer/src/autoware_auto.cpp
  external/concealer/src/autoware_universe.cpp
  mock/cpp_mock_scenarios/CMakeLists.txt
  openscenario/openscenario_interpreter/CMakeLists.txt
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/src/conversions.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_state.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_state.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: dependency

#698 fix sim model ideal steer acc geard
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_ideal_steer_acc_geared.hpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
Labels: bug

#702 fix: no perform method in str object
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bug

#703 check yaw difference
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/behavior_tree_plugin/package.xml
  simulation/behavior_tree_plugin/src/action_node.cpp
Labels: bug

#704 Feature/autoware external api
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/define_macro.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/include/concealer/undefine_macro.hpp
  external/concealer/package.xml
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/user_defined_value_condition_example/package.xml
  openscenario/user_defined_value_condition_example/src/timeout.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: feature

#707 fix sim_model_delay_steer_acc_geard model
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_delay_steer_acc_geared.hpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_delay_steer_acc_geared.cpp
Labels: bug

#706 fix hard coded parameter in hermite curve class
  simulation/traffic_simulator/src/math/hermite_curve.cpp
Labels: bug

#709 Feature/waypoint offset
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/lane_change_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/math/bounding_box.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/catmull_rom_spline.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/linear_algebra.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/bounding_box.cpp
  simulation/traffic_simulator/src/math/catmull_rom_spline.cpp
  simulation/traffic_simulator/src/math/linear_algebra.cpp
Labels: bug, feature

#713 Fix/interpreter/traffic signal state action
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state_action.cpp
Labels: bug
