Repository tier4/scenario_simulator_v2, pull requests merged in 2022-08, with the labels that each got.

#847 [OpenSCENARIO] Support ValueConstraint
  common/math/geometry/src/polygon/polygon.cpp
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_declaration.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/rule.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_constraint.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_constraint_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/requires.hpp
  openscenario/openscenario_interpreter/src/syntax/parameter_declaration.cpp
  openscenario/openscenario_interpreter/src/syntax/rule.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/value_constraint.cpp
  openscenario/openscenario_interpreter/src/syntax/value_constraint_group.cpp
  openscenario/openscenario_msgs/CMakeLists.txt
  openscenario/openscenario_msgs/msg/ParameterDeclaration.msg
  openscenario/openscenario_msgs/msg/ValueConstraint.msg
  openscenario/openscenario_msgs/msg/ValueConstraintGroup.msg
  openscenario/user_defined_value_condition_example/src/count_up.cpp
  openscenario/user_defined_value_condition_example/src/timeout.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid_cell.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_generator.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid_cell.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_generator.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_sensor.cpp
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature

#851 Feature/sync release note
  .github/workflows/SyncReleaseNote.yaml
Labels: documentation

#855 fix ci error
  .github/workflows/Documentation.yaml
  .github/workflows/ScenarioTest.yaml
Labels: bug

#857 remove unused environment variable
  .github/workflows/ScenarioTest.yaml
  dependency_humble.repos
  openscenario/openscenario_visualization/CMakeLists.txt
  openscenario/openscenario_visualization/package.xml
Labels: bug

#860 Update document
  docs/developer_guide/OpenSCENARIOSupport.md
Labels: documentation

#864 enable retry toLaneletPose function
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: feature

#854 Remove CollisionMetric and StandstillMetric
  docs/ReleaseNotes.md
  docs/developer_guide/Metrics.md
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/metrics/collision_metric.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/standstill_metric.hpp
  simulation/traffic_simulator/src/metrics/collision_metric.cpp
  simulation/traffic_simulator/src/metrics/standstill_metric.cpp
Labels: cleanup

#852 Refactor Catalog function
  .github/workflows/custom_spell.json
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/catalog_reference.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_assignments.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/src/syntax/assign_controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/assign_route_action.cpp
  openscenario/openscenario_interpreter/src/syntax/catalog_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_object.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
Labels: feature, refactor

#868 update release note
  docs/ReleaseNotes.md
Labels: release, release note

#863 Delete `lanelet2_extension_psim` / Remove -r option from `rosdep install` command to catch rosdep errors on CI workflow
  .github/workflows/BuildIsolate.yaml
  .github/workflows/ScenarioTest.yaml
  .github/workflows/custom_spell.json
  .linelint.yml
  Dockerfile
  dependency_galactic.repos
  dependency_humble.repos
  docs/ReleaseNotes.md
  docs/user_guide/deprected/lanelet2_extension_psim/README.md
  external/lanelet2_extension_psim/CHANGELOG.rst
  external/lanelet2_extension_psim/CMakeLists.txt
  external/lanelet2_extension_psim/README.md
  external/lanelet2_extension_psim/docs/detection_area.png
  external/lanelet2_extension_psim/docs/extra_lanelet_subtypes.md
  external/lanelet2_extension_psim/docs/extra_regulatory_elements.md
  external/lanelet2_extension_psim/docs/lanelet2_format_extension.md
  external/lanelet2_extension_psim/docs/light_bulbs.png
  external/lanelet2_extension_psim/docs/pedestrian_lane.svg
  external/lanelet2_extension_psim/docs/road_mark.png
  external/lanelet2_extension_psim/docs/road_shoulder.svg
  external/lanelet2_extension_psim/docs/traffic_light.png
  external/lanelet2_extension_psim/docs/traffic_light_regulatory_element.png
  external/lanelet2_extension_psim/docs/turn_direction.png
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/io/autoware_osm_parser.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/projection/mgrs_projector.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/autoware_traffic_light.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/detection_area.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/no_stopping_area.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/road_marking.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/virtual_traffic_light.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/utility/message_conversion.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/utility/query.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/utility/utilities.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/visualization/visualization.hpp
  external/lanelet2_extension_psim/lib/autoware_osm_parser.cpp
  external/lanelet2_extension_psim/lib/autoware_traffic_light.cpp
  external/lanelet2_extension_psim/lib/detection_area.cpp
  external/lanelet2_extension_psim/lib/message_conversion.cpp
  external/lanelet2_extension_psim/lib/mgrs_projector.cpp
  external/lanelet2_extension_psim/lib/no_stopping_area.cpp
  external/lanelet2_extension_psim/lib/query.cpp
  external/lanelet2_extension_psim/lib/road_marking.cpp
  external/lanelet2_extension_psim/lib/utilities.cpp
  external/lanelet2_extension_psim/lib/virtual_traffic_light.cpp
  external/lanelet2_extension_psim/lib/visualization.cpp
  external/lanelet2_extension_psim/package.xml
  external/lanelet2_extension_psim/src/sample_code.cpp
  external/lanelet2_extension_psim/src/validation.cpp
  external/lanelet2_extension_psim/test/src/test_message_conversion.cpp
  external/lanelet2_extension_psim/test/src/test_projector.cpp
  external/lanelet2_extension_psim/test/src/test_query.cpp
  external/lanelet2_extension_psim/test/src/test_regulatory_elements.cpp
  external/lanelet2_extension_psim/test/src/test_utilities.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  test_runner/random_test_runner/src/lanelet_utils.cpp
Labels: bug, github actions
