Repository tier4/scenario_simulator_v2, pull requests merged in 2022-06, with the labels that each got.

#750 Fix/interpreter/missing autoware launch
  docs/ReleaseNotes.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/task_queue.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: feature

#795 change logics for checking solution
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/math/hermite_curve.cpp
  simulation/traffic_simulator/test/src/math/test_hermite_curve.cpp
Labels: bug

#800 Fix #799
  .github/ISSUE_TEMPLATE/release.md
Labels: bug, documentation

#797 Feature/occupancy grid sensor
  docs/developer_guide/ZeroMQ.md
  docs/etc/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/src/syntax/scenario_object.cpp
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/grid_cell.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_generator.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/primitives/box.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/primitives/primitive.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/grid_cell.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_generator.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/primitives/box.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/primitives/primitive.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: feature

#807 Feature/get distance to lane bound
  docs/etc/ReleaseNotes.md
  mock/cpp_mock_scenarios/src/measurement/CMakeLists.txt
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/math/polygon.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/distance.cpp
  simulation/traffic_simulator/src/math/polygon.cpp
Labels: feature

#804 feat(api): change set/engage to external api
  docs/etc/ReleaseNotes.md
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/dirty_hack.hpp
Labels: improvement

#793 fix: modify build error in humble
  .github/workflows/Build.yaml
  .github/workflows/BuildIsolate.yaml
  common/scenario_simulator_exception/CMakeLists.txt
  common/scenario_simulator_exception/include/scenario_simulator_exception/concatenate.hpp
  dependency_humble.repos
  docs/etc/ReleaseNotes.md
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/continuous_transform_broadcaster.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/lanelet2_extension_psim/CMakeLists.txt
  external/lanelet2_extension_psim/lib/query.cpp
  external/lanelet2_extension_psim/package.xml
  mock/cpp_mock_scenarios/CMakeLists.txt
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/console/escape_sequence.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/console/is_console.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/print.hpp
  openscenario/openscenario_visualization/CMakeLists.txt
  openscenario/openscenario_visualization/include/openscenario_visualization/context_panel_plugin.hpp
  openscenario/openscenario_visualization/include/openscenario_visualization/openscenario_visualization_component.hpp
  openscenario/openscenario_visualization/package.xml
  openscenario/openscenario_visualization/src/context_panel_plugin.cpp
  openscenario/openscenario_visualization/src/openscenario_visualization_component.cpp
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/math/transform.cpp
  simulation/traffic_simulator/src/metrics/out_of_range_metric.cpp
  test_runner/random_test_runner/CMakeLists.txt
Labels: bug

#810 update Release Note
  docs/etc/ReleaseNotes.md
Labels: release, release note

#813 add missing boost depend
  common/simple_junit/package.xml
  external/concealer/package.xml
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/user_defined_value_condition_example/package.xml
  simulation/simulation_interface/package.xml
Labels: dependency

#809 Feature/get relative pose with lane pose
  docs/etc/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: feature

#805 Doc/4th improvement
  .github/workflows/SpellCheck.yaml
  .github/workflows/SpellCheckAll.yaml
  .github/workflows/custom_spell.json
  CONTRIBUTING.md
  docs/README.md
  docs/ReleaseNotes.md
  docs/developer_guide/BehaviorPlugin.md
  docs/developer_guide/CONTRIBUTING.md
  docs/developer_guide/Communication.md
  docs/developer_guide/NPCBehavior.md
  docs/developer_guide/OpenSCENARIOSupport.md
  docs/developer_guide/SimpleSensorSimulator.md
  docs/developer_guide/VehicleDynamics.md
  docs/developer_guide/ZeroMQ.md
  docs/etc/ContactUs.md
  docs/etc/HowToContribute.md
  docs/etc/LICENSE.md
  docs/stylesheet/extra.css
  docs/user_guide/deprected/RunWithAutowareArchitectureProposal.md
  docs/user_guide/lanelet2_extension_psim/README.md
  docs/user_guide/lanelet2_matching/README.md
  docs/user_guide/openscenario_interpreter/README.md
  docs/user_guide/random_test_runner/README.md
  docs/user_guide/scenario_test_runner/HowToWriteWorkflowFile.md
  docs/user_guide/scenario_test_runner/ScenarioFormatConversion.md
  external/lanelet2_extension_psim/docs/extra_regulatory_elements.md
  external/lanelet2_extension_psim/docs/lanelet2_format_extension.md
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/io/autoware_osm_parser.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/projection/mgrs_projector.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/regulatory_elements/autoware_traffic_light.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/utility/message_conversion.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/utility/query.hpp
  external/lanelet2_extension_psim/include/lanelet2_extension_psim/visualization/visualization.hpp
  external/lanelet2_extension_psim/lib/autoware_osm_parser.cpp
  external/lanelet2_extension_psim/lib/autoware_traffic_light.cpp
  external/lanelet2_extension_psim/lib/detection_area.cpp
  external/lanelet2_extension_psim/lib/query.cpp
  external/lanelet2_extension_psim/lib/road_marking.cpp
  external/lanelet2_extension_psim/lib/utilities.cpp
  external/lanelet2_extension_psim/lib/visualization.cpp
  external/lanelet2_extension_psim/package.xml
  external/lanelet2_extension_psim/src/sample_code.cpp
  mkdocs.yml
  mock/cpp_mock_scenarios/CHANGELOG.rst
  openscenario/openscenario_interpreter/src/syntax/catalog_location.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/CHANGELOG.rst
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
  simulation/traffic_simulator/test/src/math/test_catmull_rom_spline.cpp
Labels: documentation, cleanup, improvement

#825 fix URL in https://github.com/tier4/scenario_simulator_v2/issues/824
  .github/ISSUE_TEMPLATE/release.md
Labels: documentation

#822 Fix/stop position
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
Labels: bug

#818 Feature/autoware/request to cooperate
  docs/ReleaseNotes.md
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/cooperator.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/package.xml
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/cooperator.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
Labels: feature

#829 Exclude too large topic from `ros2 bag record`
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
Labels: improvement

#833 📚 Documentation : Update Topic List
  .github/workflows/DocumentationLinkCheck.yaml
  docs/developer_guide/Communication.md
Labels: documentation
