Repository tier4/scenario_simulator_v2, pull requests merged in 2022-01, with the labels that each got.

#655 Fix/galactic build
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/logging_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/reset_request_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/transition_events/transition_event.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/pedestrian/behavior_tree.cpp
  simulation/behavior_tree_plugin/src/transition_events/logging_event.cpp
  simulation/behavior_tree_plugin/src/transition_events/reset_request_event.cpp
  simulation/behavior_tree_plugin/src/transition_events/transition_event.cpp
  simulation/behavior_tree_plugin/src/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  test_runner/random_test_runner/include/random_test_runner/file_interactions/junit_xml_reporter.hpp
  test_runner/random_test_runner/include/random_test_runner/file_interactions/yaml_test_params_saver.hpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/test_executor.cpp
  test_runner/random_test_runner/src/test_randomizer.cpp
Labels: bug

#657 update Release Note for version 0.6.1
  docs/ReleaseNotes.md
Labels: release note

#581 Matsuura/feature/add time to panel
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter_msgs/msg/Context.msg
  openscenario/openscenario_visualization/include/openscenario_visualization/context_panel_plugin.hpp
  openscenario/openscenario_visualization/src/context_panel_plugin.cpp
  openscenario/openscenario_visualization/src/ui/context_panel_plugin.ui
Labels: feature

#660 Add new VehicleModelType `DELAY_STEER_VEL`
  docs/ReleaseNotes.md
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model.hpp
  simulation/traffic_simulator/include/traffic_simulator/vehicle_model/sim_model_delay_steer_vel.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/vehicle_model/sim_model_delay_steer_vel.cpp
Labels: feature

#666 update documentation about lanechange behavior
  docs/design/NPCBehavior.md
Labels: documentation

#667 Feature/control from relation
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
Labels: feature

#669 Refactor/add speed change namespace
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_dimension.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dynamics_shape.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_target_speed.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/speed_target_value_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/transition_dynamics.hpp
  openscenario/openscenario_interpreter/src/syntax/speed_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/target_speed_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/data_types.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/target_speed_planner.cpp
  simulation/traffic_simulator/src/data_type/data_types.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: refactor

#670 Feature/request speed change in pedestrian
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_lateral_velocity.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_time.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_time.cpp
  mock/cpp_mock_scenarios/src/measurement/get_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/collision.cpp
  mock/cpp_mock_scenarios/src/metrics/momentary_stop.cpp
  mock/cpp_mock_scenarios/src/metrics/out_of_range.cpp
  mock/cpp_mock_scenarios/src/metrics/reaction_time.cpp
  mock/cpp_mock_scenarios/src/metrics/standstill_duration.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  mock/cpp_mock_scenarios/src/traffic_light/phase_control.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  simulation/behavior_tree_plugin/config/pedestrian_entity_behavior.xml
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/pedestrian_action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/vehicle_action_node.hpp
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/target_speed_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/target_speed_planner.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: feature

#675 update release note for version 0.6.2
  docs/ReleaseNotes.md
Labels: release, release note

#672 Fix/interpreter/lifecycle
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/procedure.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/openscenario.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/procedure.cpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/lane_change_action.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_object.cpp
  openscenario/openscenario_interpreter/src/syntax/speed_action.cpp
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: refactor

#678 Refactor/interpreter
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
Labels: refactor

#680 Feature/speed up metrics manager
  docs/ReleaseNotes.md
  simulation/traffic_simulator/src/metrics/metrics_manager.cpp
Labels: feature

#679 Refactor/interpreter/scope
  openscenario/openscenario_interpreter/include/openscenario_interpreter/name.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/pointer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/scope.hpp
  openscenario/openscenario_interpreter/src/evaluate.cpp
  openscenario/openscenario_interpreter/src/scope.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_modify_action.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_set_action.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_controller_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signals.cpp
  test_runner/scenario_test_runner/test/scenario/autoware-simple.yaml
Labels: refactor

#683 Feature/zeromq multi client
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_server.hpp
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: feature

#681 Refactor/interpreter/storyboard element
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/story.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard_element.hpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/story.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
Labels: refactor

#685 fix zeromq document
  docs/design/ZeroMQ.md
Labels: bug, documentation

#684 Fix/virtual destructor
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/out_of_range_metric.hpp
Labels: bug
