Repository tier4/scenario_simulator_v2, pull requests merged in 2023-03, with the labels that each got.

#874 Feature/interpreter/user defined value condition
  .github/workflows/BuildIsolate.yaml
  dependency_galactic.repos
  dependency_humble.repos
  docs/ReleaseNotes.md
  docs/developer_guide/OpenSCENARIOSupport.md
  docs/user_guide/ScenarioTips.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_declaration.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_value_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_constraint.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_constraint_group.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/syntax/parameter_declaration.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_type.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/value_constraint.cpp
  openscenario/openscenario_interpreter/src/syntax/value_constraint_group.cpp
  openscenario/openscenario_interpreter_example/CMakeLists.txt
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/openscenario_interpreter_example/src/count_up.cpp
  openscenario/openscenario_interpreter_example/src/timeout.cpp
  openscenario/openscenario_msgs/CHANGELOG.rst
  openscenario/openscenario_msgs/CMakeLists.txt
  openscenario/openscenario_msgs/msg/ParameterDeclaration.msg
  openscenario/openscenario_msgs/msg/ParameterType.msg
  openscenario/openscenario_msgs/msg/ValueConstraint.msg
  openscenario/openscenario_msgs/msg/ValueConstraintGroup.msg
  openscenario/openscenario_msgs/package.xml
  openscenario/user_defined_value_condition_example/CHANGELOG.rst
  openscenario/user_defined_value_condition_example/CMakeLists.txt
  openscenario/user_defined_value_condition_example/package.xml
Labels: dependency

#972 Fix/openscenario utility/conversion
  docs/ReleaseNotes.md
  openscenario/openscenario_utility/openscenario_utility/conversion.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: improvement

#904 added ability to specify goalposes in requestAcquirePosition
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: feature, wait for regression test

#973 Feature/interpreter/probability of lost
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
Labels: feature

#975 Add UserDefinedValueCondition::currentMinimumRiskManeuverState.state/behavior with backwardcompatibility
  dependency_galactic.repos
  dependency_humble.repos
  docs/ReleaseNotes.md
  docs/developer_guide/Communication.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/package.xml
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: wait for regression test

#964 Feature/noise delay object
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
Labels: wait for regression test

#978 Feature/interpreter/relative heading condition
  docs/ReleaseNotes.md
  docs/developer_guide/OpenSCENARIOSupport.md
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/utility/service_with_validation.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature

#982 Clean dicts
  .github/workflows/SpellCheck.yaml
  .github/workflows/SpellCheckAll.yaml
  .github/workflows/custom_spell.json
  .textlintrc
  docs/user_guide/lanelet2_matching/README.md
  mkdocs.yml
Labels: refactor, cleanup

#971 Add `delay` implementation for `condition`
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition.hpp
  openscenario/openscenario_interpreter/src/syntax/condition.cpp
  openscenario/openscenario_interpreter/src/syntax/condition_edge.cpp
  test_runner/scenario_test_runner/scenario/condition.yaml
Labels: feature

#981 ref(sim_interface): AJD-697 improve zeromq port management - use a single-port
  .github/workflows/custom_spell.json
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/constants.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
Labels: refactor, improvement
