Repository tier4/scenario_simulator_v2, pull requests merged in 2023-08, with the labels that each got.

#1022 Feature/traffic simulator/follow trajectory action
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/follow_trajectory_action.hpp
  openscenario/openscenario_interpreter/src/syntax/follow_trajectory_action.cpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.hpp
  simulation/behavior_tree_plugin/package.xml
  simulation/behavior_tree_plugin/src/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/do_nothing_plugin/include/do_nothing_plugin/plugin.hpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_trajectory.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/follow_trajectory.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator_msgs/CMakeLists.txt
  simulation/traffic_simulator_msgs/msg/Polyline.msg
  simulation/traffic_simulator_msgs/msg/PolylineTrajectory.msg
  simulation/traffic_simulator_msgs/msg/Vertex.msg
Labels: feature, interface breaking

#1046 fix(openscenario_interpreter): run scenario in row (Entity : "ego" does not exist)
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: bug

#1031 feat(openscenario_interpreter): Remove the ability to verify that scenario success/error is the expected result
  docs/developer_guide/OpenSCENARIOSupport.md
  docs/user_guide/scenario_test_runner/HowToWriteWorkflowFile.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_preprocessor/include/openscenario_preprocessor/openscenario_preprocessor.hpp
  openscenario/openscenario_preprocessor_msgs/srv/Derive.srv
  openscenario/openscenario_preprocessor_msgs/srv/Load.srv
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/scenario/failure.yaml
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/resources/workflow_schema.yaml
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/scenario_test_runner/workflow.py
Labels: improvement

#1065 fix/pr-1018-fix
  openscenario/openscenario_interpreter/src/syntax/acquire_position_action.cpp
  openscenario/openscenario_interpreter/src/syntax/position.cpp
Labels: wait for regression test

#1061 Feature/traffic simulator/follow trajectory action 2
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/proto/traffic_simulator_msgs.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: feature

#1056 Feature/interpreter/sensor detection range
  docs/developer_guide/ConfiguringPerceptionTopics.md
  docs/image/simple_sensor_simulator_detection_sensor.drawio
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/raycaster.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/raycaster.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
  test_runner/scenario_test_runner/scenario/Property.detectionSensorRange.yaml
Labels: feature, wait for regression test

#1024 Feature/perception ground truth
  docs/ReleaseNotes.md
  docs/developer_guide/Communication.md
  docs/developer_guide/ConfiguringPerceptionTopics.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/src/helper/helper.cpp
  test_runner/scenario_test_runner/scenario/Property.detectedObjectGroundTruthPublishingDelay.yaml
Labels: feature, wait for regression test

#1074 Fix/clock
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/error.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/lidar/lidar_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/simulation_clock/simulation_clock.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/simulation_clock/simulation_clock.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: bug
