Repository tier4/scenario_simulator_v2, pull requests merged in 2023-11, with the labels that each got.

#1121 Fix/sign of relative distance
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.RelativeDistanceConditionFreespace.yaml
Labels: bug

#1127 Fix/document url
  docs/developer_guide/BehaviorPlugin.md
  docs/developer_guide/TrafficSimulator.md
Labels: bug, documentation

#1111 Add `PseudoTrafficSignalDetectorConfidenceSetAction@v1`
  docs/ReleaseNotes.md
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/do_nothing_plugin/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  test_runner/random_test_runner/CMakeLists.txt
  test_runner/scenario_test_runner/scenario/CustomCommandAction.PseudoTrafficSignalDetectorConfidenceSetAction@v1.yaml
Labels: wait for regression test

#1126 fix(launch): remove name keyword from nodes in launch file
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_value_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  openscenario/openscenario_preprocessor/src/openscenario_preprocessor.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test

#1140 Update ZeroMQ.md
  docs/developer_guide/ZeroMQ.md
Labels: documentation

#1137 fix(follow_trajectory): fix orientation for zero velocity vector (inactivity)
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
Labels: bug
