Repository tier4/scenario_simulator_v2, pull requests merged in 2023-09, with the labels that each got.

#1058 ref(zeromq): restore repeated in UpdateEntityStatus
  common/math/geometry/include/geometry/vector3/hypot.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: refactor

#1084 update release note
  docs/ReleaseNotes.md
  mkdocs.yml
Labels: release, release note

#1086 Release 0.8.0
  common/math/arithmetic/CHANGELOG.rst
  common/math/arithmetic/package.xml
  common/math/geometry/CHANGELOG.rst
  common/math/geometry/package.xml
  common/scenario_simulator_exception/CHANGELOG.rst
  common/scenario_simulator_exception/package.xml
  common/simple_junit/CHANGELOG.rst
  common/simple_junit/package.xml
  common/status_monitor/CHANGELOG.rst
  common/status_monitor/package.xml
  external/concealer/CHANGELOG.rst
  external/concealer/package.xml
  external/lanelet2_matching/CHANGELOG.rst
  external/lanelet2_matching/package.xml
  map/kashiwanoha_map/CHANGELOG.rst
  map/kashiwanoha_map/package.xml
  mock/cpp_mock_scenarios/CHANGELOG.rst
  mock/cpp_mock_scenarios/package.xml
  openscenario/openscenario_experimental_catalog/CHANGELOG.rst
  openscenario/openscenario_experimental_catalog/package.xml
  openscenario/openscenario_interpreter/CHANGELOG.rst
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter_example/CHANGELOG.rst
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/openscenario_interpreter_msgs/CHANGELOG.rst
  openscenario/openscenario_interpreter_msgs/package.xml
  openscenario/openscenario_preprocessor/CHANGELOG.rst
  openscenario/openscenario_preprocessor/package.xml
  openscenario/openscenario_preprocessor_msgs/CHANGELOG.rst
  openscenario/openscenario_preprocessor_msgs/package.xml
  openscenario/openscenario_utility/CHANGELOG.rst
  openscenario/openscenario_utility/package.xml
  openscenario/openscenario_visualization/CHANGELOG.rst
  openscenario/openscenario_visualization/package.xml
  scenario_simulator_v2/CHANGELOG.rst
  scenario_simulator_v2/package.xml
  simulation/behavior_tree_plugin/CHANGELOG.rst
  simulation/behavior_tree_plugin/package.xml
  simulation/do_nothing_plugin/CHANGELOG.rst
  simulation/do_nothing_plugin/package.xml
  simulation/simple_sensor_simulator/CHANGELOG.rst
  simulation/simple_sensor_simulator/package.xml
  simulation/simulation_interface/CHANGELOG.rst
  simulation/simulation_interface/package.xml
  simulation/traffic_simulator/CHANGELOG.rst
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator_msgs/CHANGELOG.rst
  simulation/traffic_simulator_msgs/package.xml
  test_runner/random_test_runner/CHANGELOG.rst
  test_runner/random_test_runner/package.xml
  test_runner/scenario_test_runner/CHANGELOG.rst
  test_runner/scenario_test_runner/package.xml
Labels: release

#1027 Feature/new traffic light
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/traffic_lights/traffic_lights_detector.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/traffic_lights/traffic_lights_detector.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/configurable_rate_updater.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_marker_publisher.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_publisher.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/configurable_rate_updater.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_marker_publisher.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_publisher.cpp
  simulation/traffic_simulator/src/traffic_lights/v2i_traffic_light_publisher.cpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/src/data_types.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test

#1083 fix/distance-condition
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
Labels: bug, wait for regression test

#1087 Feature/drop galactic support
  .github/workflows/BuildAndRun.yaml
  .github/workflows/Docker.yaml
  common/math/geometry/CMakeLists.txt
  common/math/geometry/src/transform.cpp
  dependency_galactic.repos
  docs/user_guide/BuildInstructions.md
  docs/user_guide/QuickStart.md
  docs/user_guide/RunWithDocker.md
  docs/user_guide/deprected/RunWithAutowareArchitectureProposal.md
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/continuous_transform_broadcaster.hpp
  mock/cpp_mock_scenarios/CMakeLists.txt
  openscenario/openscenario_interpreter/CMakeLists.txt
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/do_nothing_plugin/CMakeLists.txt
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  test_runner/random_test_runner/CMakeLists.txt
Labels: wait for regression test

#1063 remove lanalet2_matching package source code
  .github/workflows/custom_spell.json
  .gitignore
  docs/user_guide/lanelet2_matching/README.md
  external/lanelet2_matching/CHANGELOG.rst
  external/lanelet2_matching/CMakeLists.txt
  external/lanelet2_matching/custom.cmake
  external/lanelet2_matching/include/lanelet2_matching/Exceptions.h
  external/lanelet2_matching/include/lanelet2_matching/LaneletMatching.h
  external/lanelet2_matching/include/lanelet2_matching/Types.h
  external/lanelet2_matching/include/lanelet2_matching/Utilities.h
  external/lanelet2_matching/package.xml
  external/lanelet2_matching/src/LaneletMatching.cpp
  external/lanelet2_matching/src/Utilities.cpp
  external/lanelet2_matching/test/lanelet2_matching.cpp
  external/lanelet2_matching/test/lanelet2_matching_integration.cpp
  external/lanelet2_matching/test/mapping_example.osm
Labels: dependency, wait for regression test

#1069 Feature/traffic simulator/follow trajectory action 3
  simulation/behavior_tree_plugin/src/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_trajectory.hpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  test_runner/scenario_test_runner/scenario/RoutingAction.FollowTrajectoryAction-autoware.yaml
Labels: feature

#1090 Refactor/lanelet ID
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state.cpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/do_nothing_plugin/include/do_nothing_plugin/plugin.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/entity_status.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/lane_change.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/lanelet_pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/cache.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/route_planner.cpp
  simulation/traffic_simulator/src/data_type/entity_status.cpp
  simulation/traffic_simulator/src/data_type/lanelet_pose.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/test_hdmap_utils.cpp
Labels: refactor
