Repository tier4/scenario_simulator_v2, pull requests merged in 2023-05, with the labels that each got.

#969 feat(concealer, traffic_sim): ss2/AWSIM connection: concealer split
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/dirty_hack.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/include/concealer/utility/publisher_wrapper.hpp
  external/concealer/include/concealer/utility/service_with_validation.hpp
  external/concealer/include/concealer/utility/subscriber_wrapper.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  external/concealer/src/task_queue.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/src/test_executor.cpp
Labels: refactor

#1002 Feature/interpreter/fault injection
  docs/ReleaseNotes.md
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/regex/function_call_expression.hpp
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature

#1008 doc: fix links in SimpleSensorSimulator.md
  docs/developer_guide/SimpleSensorSimulator.md
Labels: bug, documentation

#1007 Documentation/interpreter/detected object
  .github/workflows/custom_spell.json
  docs/developer_guide/ConfiguringPerceptionTopics.md
  test_runner/scenario_test_runner/scenario/Property.detectedObjectMissingProbability.yaml
  test_runner/scenario_test_runner/scenario/Property.detectedObjectPositionStandardDeviation.yaml
  test_runner/scenario_test_runner/scenario/Property.detectedObjectPublishingDelay.yaml
Labels: documentation

#996 Fix/get s value
  .github/workflows/custom_spell.json
  common/math/geometry/include/geometry/solver/polynomial_solver.hpp
  common/math/geometry/include/geometry/spline/catmull_rom_spline.hpp
  common/math/geometry/package.xml
  common/math/geometry/src/solver/polynomial_solver.cpp
  common/math/geometry/src/spline/hermite_curve.cpp
  common/math/geometry/test/test_catmull_rom_spline.cpp
  common/math/geometry/test/test_polynomial_solver.cpp
Labels: bug, wait for regression test
