Repository tier4/scenario_simulator_v2, pull requests merged in 2023-01, with the labels that each got.

#927 chore(concealer): remove unused had_map_route msg
  external/concealer/include/concealer/autoware_universe.hpp
Labels: wait for regression test

#946 update stopping behavior
  docs/ReleaseNotes.md
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/traffic_simulator_msgs/msg/DynamicConstraints.msg
Labels: interface breaking

#945 Feature/get lateral distance
  .github/workflows/Build.yaml
  .github/workflows/BuildIsolate.yaml
  .github/workflows/Docker.yaml
  .github/workflows/ScenarioTest.yaml
  docs/ReleaseNotes.md
  mock/cpp_mock_scenarios/src/measurement/CMakeLists.txt
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: feature

#950 update trigger for heavy ci workflows
  .github/workflows/Build.yaml
  .github/workflows/Docker.yaml
  .github/workflows/ScenarioTest.yaml
Labels: refactor, github actions

#858 Move traveled distance functionality to `traffic_simulator::API`
  .github/workflows/custom_spell.json
  .textlintrc
  docs/ReleaseNotes.md
  docs/developer_guide/Metrics.md
  mock/cpp_mock_scenarios/src/metrics/CMakeLists.txt
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/job/job.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/metrics.hpp
  simulation/traffic_simulator/include/traffic_simulator/metrics/traveled_distance_metric.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/metrics/traveled_distance_metric.cpp
Labels: wait for regression test

#951 Fix/warnings
  .github/workflows/custom_spell.json
  .gitignore
  common/math/geometry/CMakeLists.txt
  mock/cpp_mock_scenarios/CMakeLists.txt
  openscenario/openscenario_utility/setup.py
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/traffic_simulator/CMakeLists.txt
  test_runner/scenario_test_runner/setup.py
Labels: wait for regression test

#952 Feature/interpreter/catalog
  openscenario/openscenario_experimental_catalog/CMakeLists.txt
  openscenario/openscenario_experimental_catalog/package.xml
  openscenario/openscenario_experimental_catalog/vehicle/sample_vehicle.yaml
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature

#956 clean up custom_spell.json
  .github/workflows/custom_spell.json
Labels: refactor, cleanup, github actions

#959 Revert "clean up custom_spell.json"
  .github/workflows/custom_spell.json
Labels: revert

#955 Mock build switching
  .github/workflows/Build.yaml
  .github/workflows/BuildIsolate.yaml
  .github/workflows/ScenarioTest.yaml
  .github/workflows/custom_spell.json
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/cmake/add_cpp_mock_scenario_test.cmake
Labels: feature

#954 Fix/python installation
  .github/workflows/ScenarioTest.yaml
  docs/user_guide/scenario_test_runner/ScenarioFormatConversion.md
  openscenario/openscenario_interpreter/src/syntax/open_scenario_category.cpp
  openscenario/openscenario_preprocessor/src/openscenario_preprocessor.cpp
  openscenario/openscenario_utility/CMakeLists.txt
  openscenario/openscenario_utility/openscenario_utility/__init__.py
  openscenario/openscenario_utility/openscenario_utility/conversion.py
  openscenario/openscenario_utility/openscenario_utility/scenario_validation.py
  openscenario/openscenario_utility/openscenario_utility/validation.py
  openscenario/openscenario_utility/package.xml
  openscenario/openscenario_utility/resource/openscenario_utility
  openscenario/openscenario_utility/setup.cfg
  openscenario/openscenario_utility/setup.py
  test_runner/scenario_test_runner/CMakeLists.txt
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/package.xml
  test_runner/scenario_test_runner/resource/scenario_test_runner
  test_runner/scenario_test_runner/scenario_test_runner/__init__.py
  test_runner/scenario_test_runner/scenario_test_runner/lifecycle_controller.py
  test_runner/scenario_test_runner/scenario_test_runner/resources/workflow_schema.yaml
  test_runner/scenario_test_runner/scenario_test_runner/result_checker.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/scenario_test_runner/shutdown_once.py
  test_runner/scenario_test_runner/scenario_test_runner/workflow.py
  test_runner/scenario_test_runner/setup.cfg
  test_runner/scenario_test_runner/setup.py
Labels: dependency

#958 lost object with probability parameter
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
Labels: wait for regression test
