Repository tier4/scenario_simulator_v2, pull requests merged in 2023-04, with the labels that each got.

#977 Add `model3d` field to entity object
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/misc_object.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/pedestrian.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/vehicle.hpp
  openscenario/openscenario_interpreter/src/syntax/misc_object.cpp
  openscenario/openscenario_interpreter/src/syntax/pedestrian.cpp
  openscenario/openscenario_interpreter/src/syntax/vehicle.cpp
Labels: feature, small feature, wait for regression test

#986 Feature/interpreter/publishing delay
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
Labels: feature

#980 Add support for EnvironmentAction syntax
  .github/workflows/custom_spell.json
  docs/ReleaseNotes.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/dome_image.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/environment.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/environment_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/fog.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/fractional_cloud_cover.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/global_action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/precipitation.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/precipitation_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/road_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/sun.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/time_of_day.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/weather.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/wetness.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/wind.hpp
  openscenario/openscenario_interpreter/src/syntax/catalog.cpp
  openscenario/openscenario_interpreter/src/syntax/dome_image.cpp
  openscenario/openscenario_interpreter/src/syntax/environment.cpp
  openscenario/openscenario_interpreter/src/syntax/environment_action.cpp
  openscenario/openscenario_interpreter/src/syntax/fog.cpp
  openscenario/openscenario_interpreter/src/syntax/fractional_cloud_cover.cpp
  openscenario/openscenario_interpreter/src/syntax/global_action.cpp
  openscenario/openscenario_interpreter/src/syntax/precipitation.cpp
  openscenario/openscenario_interpreter/src/syntax/precipitation_type.cpp
  openscenario/openscenario_interpreter/src/syntax/road_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/sun.cpp
  openscenario/openscenario_interpreter/src/syntax/time_of_day.cpp
  openscenario/openscenario_interpreter/src/syntax/weather.cpp
  openscenario/openscenario_interpreter/src/syntax/wetness.cpp
  openscenario/openscenario_interpreter/src/syntax/wind.cpp
  test_runner/scenario_test_runner/scenario/Environment.yaml
Labels: feature, wait for regression test

#988 return std::nullopt in optional_position function
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
Labels: wait for regression test

#993 add const
  common/math/geometry/include/geometry/spline/catmull_rom_spline.hpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
Labels: wait for regression test
