Repository tier4/scenario_simulator_v2, pull requests merged in 2024-03, with the labels that each got.

#1205 Update and refactor workflows
  .github/workflows/BuildAndRun.yaml
  .github/workflows/CheckBranchUpToDate.yaml
  .github/workflows/Documentation.yaml
  .github/workflows/DocumentationLinkCheck.yaml
  .github/workflows/InterfaceUpdateNotification.yaml
  .github/workflows/LineLint.yaml
  .github/workflows/Release.yaml
  .github/workflows/SimModelUpdateNotification.yaml
  .github/workflows/SpellCheck.yaml
  .github/workflows/SpellCheckAll.yaml
Labels: refactor, bump patch

#1209 Consider road slope in distance measurement and entity poses
  .github/workflows/SimModelUpdateNotification.yaml
  common/math/geometry/include/geometry/polygon/line_segment.hpp
  common/math/geometry/include/geometry/spline/catmull_rom_spline.hpp
  common/math/geometry/include/geometry/spline/hermite_curve.hpp
  common/math/geometry/src/polygon/line_segment.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  common/math/geometry/src/spline/hermite_curve.cpp
  common/math/geometry/test/test_catmull_rom_spline.cpp
  common/math/geometry/test/test_line_segment.cpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/world_position.hpp
  openscenario/openscenario_interpreter/src/syntax/acquire_position_action.cpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/double.cpp
  openscenario/openscenario_interpreter/src/syntax/position.cpp
  openscenario/openscenario_interpreter/src/syntax/reach_position_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/teleport_action.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_delay_steer_map_acc_geared.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_sensor.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/speed_change.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  test_runner/random_test_runner/include/random_test_runner/lanelet_utils.hpp
  test_runner/random_test_runner/src/lanelet_utils.cpp
  test_runner/random_test_runner/src/test_randomizer.cpp
  test_runner/random_test_runner/test/test_lanelet_utils.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.DistanceConditionFreespace.yaml
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.RelativeDistanceConditionFreespace.yaml
Labels: wait for regression test, bump minor

#1213 Fix automated dependencies update check workflow
  .github/workflows/CheckMessageDepsUpdate.yaml
Labels: bump patch

#1214 Delete edited trigger from release workflow
  .github/workflows/Release.yaml
Labels: bump patch

#1201 Feature/set behavior parameter in object controller
  mock/cpp_mock_scenarios/src/speed_planning/CMakeLists.txt
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_limit.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/longitudinal_speed_planning.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/scenario/set_behavior_parameters_in_object_controller.yaml
Labels: wait for regression test, bump minor

#1155 Random test runner AWSIM support
  docs/user_guide/random_test_runner/QuickStart.md
  docs/user_guide/random_test_runner/Usage.md
  docs/user_guide/random_test_runner/img/random_test_runner_awsim.png
  test_runner/random_test_runner/include/random_test_runner/data_types.hpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/src/data_types.cpp
  test_runner/random_test_runner/src/random_test_runner.cpp
  test_runner/random_test_runner/test/test_data_types.cpp
  test_runner/random_test_runner/test/test_test_executor.cpp
Labels: bump minor

#1210 Feature/reset behavior plugin
  mock/cpp_mock_scenarios/src/behavior_plugin/load_do_nothing_plugin.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: wait for regression test, bump minor

#1218 Fix broken document
  docs/developer_guide/ZeroMQ.md
Labels: bump patch

#1200 Feature/simple sensor simulator/custom noise
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
Labels: bump minor
