Repository tier4/scenario_simulator_v2, pull requests merged in 2024-06, with the labels that each got.

#1271 fix rviz config
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
Labels: bump patch

#1270 Feature/unit tests/hdmap utils
  simulation/traffic_simulator/test/CMakeLists.txt
  simulation/traffic_simulator/test/map/crossroads_with_stoplines/lanelet2_map.osm
  simulation/traffic_simulator/test/map/empty/lanelet2_map.osm
  simulation/traffic_simulator/test/map/four_track_highway/lanelet2_map.osm
  simulation/traffic_simulator/test/src/expect_eq_macros.hpp
  simulation/traffic_simulator/test/src/hdmap_utils/CMakeLists.txt
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/test_hdmap_utils.cpp
Labels: bump patch

#1269 Feature/unit tests/longitudinal speed planner
  simulation/traffic_simulator/test/CMakeLists.txt
  simulation/traffic_simulator/test/src/behavior/CMakeLists.txt
  simulation/traffic_simulator/test/src/behavior/test_longitudinal_speed_planner.cpp
Labels: bump patch

#1226 fix(follow_trajectory_action): adapt to work with considering slopes
  simulation/behavior_tree_plugin/src/pedestrian/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_trajectory.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: bump minor

#1279 fix -wreorder warning
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
Labels: bump patch

#1012 Fix/interpreter/fault injection action
  openscenario/openscenario_interpreter/src/syntax/custom_command_action.cpp
Labels: bug, bump patch

#1284 Optimize `EntityManager::broadcastEntityTransform` to Execute Only Once
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: wait for regression test, bump patch

#1289 Revert "Optimize `EntityManager::broadcastEntityTransform` to Execute Only Once"
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: bump patch

#1275 Feature: improve ROS parameter handling
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/node_parameters.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: wait for regression test, bump patch

#1291 Feature/simple sensor simulator unit test
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/test/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/expect_eq_macros.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_raycaster.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_raycaster.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/occupancy_grid/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/occupancy_grid/test_grid_traversal.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/occupancy_grid/test_grid_traversal.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_box.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_vertex.cpp
Labels: bump patch

#1299 Fix/remove arm build test
  .github/workflows/Docker.yaml
  poetry.lock
Labels: bump patch

#1286 Feature/unit tests/misc object entity
  simulation/traffic_simulator/test/src/entity/CMakeLists.txt
  simulation/traffic_simulator/test/src/entity/test_misc_object_entity.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/helper_functions.hpp
Labels: bump patch

#1292 add API::clearRoute()
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: wait for regression test, bump minor

#1293 Optimize entity frame computation.
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: wait for regression test, bump patch

#1304 fix: Automated branch deletion is not working properly
  .github/workflows/Release.yaml
Labels: bump patch
