Repository tier4/scenario_simulator_v2, pull requests merged in 2024-05, with the labels that each got.

#1237 Feature/perf
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump patch

#1238 Publish `entities` frame
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
Labels: wait for regression test, bump patch

#1239 Feature/speed up set other status
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: wait for regression test, bump patch

#1198 Feature/respawn entity
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/respawn_ego/CMakeLists.txt
  mock/cpp_mock_scenarios/src/respawn_ego/respawn_ego.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: bump minor

#1244 Use "awesome-pages"
  docs/.pages
  docs/developer_guide/.pages
  docs/developer_guide/lane_pose_calculation/.pages
  docs/release/.pages
  docs/release/ReleaseNotes.md
  docs/user_guide/.pages
  docs/user_guide/random_test_runner/.pages
  docs/user_guide/scenario_editor/.pages
  docs/user_guide/scenario_test_runner/.pages
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: bump patch

#1246 fix link error of release note
  CONTRIBUTING.md
Labels: bump patch

#1247 Fix/contributing md
  .github/workflows/BuildAndRun.yaml
  .github/workflows/Docker.yaml
  CONTRIBUTING.md
Labels: bump patch

#1245 remove unused member values in behavior plugin
  docs/developer_guide/BehaviorPlugin.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/do_nothing_plugin/include/do_nothing_plugin/plugin.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: wait for regression test, bump patch

#1228 Add `openscenario_validator` package
  .github/workflows/custom_spell.json
  openscenario/openscenario_validator/.gitignore
  openscenario/openscenario_validator/CMakeLists.txt
  openscenario/openscenario_validator/configure/OpenSCENARIO-1.2.xsd
  openscenario/openscenario_validator/configure/OpenSCENARIO-1.3.xsd
  openscenario/openscenario_validator/configure/schema.cpp
  openscenario/openscenario_validator/include/openscenario_validator/schema.hpp
  openscenario/openscenario_validator/include/openscenario_validator/validator.hpp
  openscenario/openscenario_validator/package.xml
  openscenario/openscenario_validator/src/validator_command.cpp
Labels: wait for regression test, bump minor

#1255 Fix/visualization
  common/math/geometry/src/linear_algebra.cpp
  mock/cpp_mock_scenarios/rviz/mock_test.rviz
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
Labels: wait for regression test, bump patch

#1231 Feature/traffic source
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_source/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_delay.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_high_rate.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_large.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_mixed.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_multiple.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_outside_lane.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_pedestrian.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_vehicle.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_module_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_sink.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_source.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/helper/helper.cpp
  simulation/traffic_simulator/src/traffic/traffic_controller.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
  simulation/traffic_simulator/src/traffic/traffic_source.cpp
Labels: bump minor

#1233 ref(traffic_simulator): implement separate class for distance calculations, adapt make positions in SimulatorCore
  common/math/geometry/include/geometry/bounding_box.hpp
  common/math/geometry/src/bounding_box.cpp
  common/math/geometry/src/intersection/collision.cpp
  common/math/geometry/test/test_bounding_box.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/lane_position.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/world_position.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/entity_status.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/lanelet_pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/pose.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
Labels: bump major

#1254 refactor `openscenario validator` package
  openscenario/openscenario_validator/CMakeLists.txt
  openscenario/openscenario_validator/configure/schema.cpp
  openscenario/openscenario_validator/include/openscenario_validator/schema.hpp
  openscenario/openscenario_validator/include/openscenario_validator/validator.hpp
  openscenario/openscenario_validator/package.xml
  openscenario/openscenario_validator/schema/OpenSCENARIO-1.2.xsd
  openscenario/openscenario_validator/schema/OpenSCENARIO-1.3.xsd
Labels: bump patch
