Repository tier4/scenario_simulator_v2, pull requests merged in 2024-11, with the labels that each got.

#1429 Add missing include
  common/math/geometry/include/geometry/vector3/normalize.hpp
  external/concealer/src/execute.cpp
Labels: bump patch

#1426 Fixed logic to remove duplicate topics.
  rviz_plugins/openscenario_visualization/src/context_panel_plugin.cpp
Labels: wait for regression test, bump patch

#1433 fix/sonor-cloud-issue-3
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/pedestrian_action_node.hpp
Labels: wait for regression test, bump patch

#1430 Code Optimization and Refactoring
  common/math/geometry/include/geometry/spline/catmull_rom_spline.hpp
  common/math/geometry/test/src/quaternion/test_quaternion.cpp
  common/math/geometry/test/src/vector3/test_truncate_custom.cpp
  common/math/geometry/test/src/vector3/test_truncate_msg.cpp
  common/status_monitor/src/status_monitor.cpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
  simulation/traffic_simulator/src/data_type/entity_status.cpp
  simulation/traffic_simulator/src/data_type/lanelet_pose.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
Labels: wait for regression test, bump patch

#1438 Add comment for empty functions.
  simulation/do_nothing_plugin/src/plugin.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
Labels: bump patch

#1403 RJD-1334/fix_longitudinal_distance
  docs/developer_guide/DistanceCalculation.md
  docs/image/lanelet_matching.png
  docs/image/shortest_l1_dash.png
  docs/image/shortest_l3.png
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.DistanceCondition.Shortest.yaml
Labels: wait for regression test, bump minor

#1404 RJD-1336/fix_request_speed_change_throws
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
Labels: wait for regression test, bump patch

#1437 extend for default lanelet matching distance for NPCs
  docs/developer_guide/lane_pose_calculation/LanePoseCalculation.md
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: bump minor

#1428 Refactor curvature sampling loop to avoid using float counter
  common/math/geometry/src/spline/hermite_curve.cpp
Labels: wait for regression test, bump patch

#1431 fix/sonor-cloud-issue
  common/math/geometry/include/geometry/bounding_box.hpp
  common/math/geometry/src/bounding_box.cpp
  rviz_plugins/openscenario_visualization/include/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.hpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/jsk_overlay_utils.cpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.cpp
Labels: wait for regression test, bump patch

#1439 fix sonor cloud issue
  common/math/geometry/include/geometry/quaternion/quaternion_to_euler.hpp
  common/math/geometry/include/geometry/spline/catmull_rom_spline_interface.hpp
  common/math/geometry/include/geometry/spline/catmull_rom_subspline.hpp
  common/math/geometry/include/geometry/spline/hermite_curve.hpp
  common/math/geometry/include/geometry/vector3/operator.hpp
  common/math/geometry/src/bounding_box.cpp
  common/math/geometry/src/intersection/intersection.cpp
  common/math/geometry/src/spline/hermite_curve.cpp
Labels: wait for regression test, bump patch

#1423 Support `ByType` element in `CollisionCondition`
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/by_object_type.hpp
  openscenario/openscenario_interpreter/src/syntax/by_object_type.cpp
  openscenario/openscenario_interpreter/src/syntax/collision_condition.cpp
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/scenario/collision_condition_by_type.yaml
Labels: feature, bump minor

#1445 Renamed lambda parameters to avoid variable shadowing.
  common/math/geometry/src/solver/polynomial_solver.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
Labels: wait for regression test, bump patch

#1421 Improve simulated manual override with `FollowTrajectoryAction`
  docs/developer_guide/.pages
  docs/developer_guide/Communication.md
  docs/developer_guide/ManualOverrideWithFollowTrajectoryAction.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/include/concealer/service_with_validation.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  external/concealer/src/task_queue.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/scenario/RoutingAction.FollowTrajectoryAction-override.yaml
Labels: bump minor

#1450 refactor HDMapUtils class about routing graph
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/data_type/routing_graph_type.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/data_type/routing_graph_type.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
Labels: wait for regression test, bump patch

#1453 Fix/interpreter/assign route action
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  test_runner/scenario_test_runner/scenario/RoutingAction.AssignRouteAction.yaml
Labels: bug, bump patch

#1451 Fix/sonor cloud issue 7
  common/math/geometry/include/geometry/intersection/collision.hpp
  common/math/geometry/src/intersection/collision.cpp
  common/math/geometry/src/polygon/line_segment.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/jsk_overlay_utils.cpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
Labels: wait for regression test, bump patch

#1447 fix pitch and slope acceleration calculation for ego vehicle
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/simple_sensor_simulator/test/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/vehicle_simulation/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/vehicle_simulation/test_ego_entity_simulation.cpp
  simulation/traffic_simulator/test/map/slope/lanelet2_map.osm
Labels: bug, bump patch

#1461 Support road shoulders as an `Entity` operating area
  map/kashiwanoha_map/map/road_shoulder_added/lanelet2_map.osm
  map/kashiwanoha_map/map/road_shoulder_added/pointcloud_map.pcd
  simulation/traffic_simulator/include/traffic_simulator/behavior/route_planner.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/routing_configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/behavior/route_planner.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/test/src/behavior/test_route_planner.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/scenario/LateralAction.LaneChangeAction-RoadShoulder.yaml
Labels: bump minor

#1435 Fix/sonarcloud warning
  simulation/behavior_tree_plugin/CMakeLists.txt
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_lane_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/pedestrian_action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/walk_straight_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_front_entity_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_lane_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/move_backward_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_stop_line_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_traffic_light_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/yield_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/lane_change_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/vehicle_action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
Labels: wait for regression test, bump patch

#1463 Refactor/interpreter
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/cmath/hypot.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entities.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/reach_position_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/reach_position_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
Labels: refactor, bump patch

#1444 RJD-1057 (2/5): Remove non-API member functions: EntityManager’s TrafficLight related member functions (tests)
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_publisher.hpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_publisher.cpp
  simulation/traffic_simulator/test/src/expect_eq_macros.hpp
  simulation/traffic_simulator/test/src/traffic_lights/CMakeLists.txt
  simulation/traffic_simulator/test/src/traffic_lights/common_test_fixtures.hpp
  simulation/traffic_simulator/test/src/traffic_lights/helper.hpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_common.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_v2i.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_v2i_new_architecture.cpp
Labels: refactor, bump patch
