Repository tier4/scenario_simulator_v2, pull requests merged in 2024-12, with the labels that each got.

#1459 Feature/relative speed condition
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/directional_dimension.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_speed_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/entity_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_speed_condition.cpp
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.RelativeSpeedCondition.yaml
Labels: feature, bump minor

#1466 Refactor/relative distance condition
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
Labels: refactor, bump patch

#1467 Refactor/distance condition
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
Labels: refactor, bump patch

#1471 Fix/sonor cloud issue 8-2
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.cpp
Labels: refactor, wait for regression test, bump patch

#1477 fix: caluculation for the gravity by slope in ego entity simulation
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/simple_sensor_simulator/test/src/vehicle_simulation/test_ego_entity_simulation.cpp
Labels: bug, bump patch

#1468 make Entity lane-changeable everywhere
  map/kashiwanoha_map/map/road_shoulder_added/lanelet2_map.osm
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/traffic_rules.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/hdmap_utils/traffic_rules.cpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
Labels: bump minor

#1474 Fix Sonor Cloud Issue8-3
  test_runner/random_test_runner/include/random_test_runner/lanelet_utils.hpp
  test_runner/random_test_runner/src/lanelet_utils.cpp
Labels: refactor, wait for regression test, bump patch

#1454 Drop support for `autoware_auto_xx_msgs`
  dependency_humble.repos
  docs/developer_guide/Communication.md
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/package.xml
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/openscenario_interpreter_example/src/timeout.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/traffic_lights/traffic_lights_detector.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_delay_steer_acc_geared.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_delay_steer_map_acc_geared.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_ideal_steer_acc_geared.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_interface.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/vehicle_model/sim_model_delay_steer_acc_geared.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/vehicle_model/sim_model_delay_steer_map_acc_geared.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/vehicle_model/sim_model_ideal_steer_acc_geared.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_raycaster.hpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/package.xml
  simulation/simulation_interface/proto/autoware_auto_control_msgs.proto
  simulation/simulation_interface/proto/autoware_control_msgs.proto
  simulation/simulation_interface/proto/autoware_vehicle_msgs.proto
  simulation/simulation_interface/proto/traffic_simulator_msgs.proto
  simulation/simulation_interface/src/conversions.cpp
  simulation/simulation_interface/test/expect_equal_macros.hpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_lights.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_publisher.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_common.cpp
  test_runner/random_test_runner/src/data_types.cpp
  test_runner/random_test_runner/test/test_data_types.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: interface breaking, bump major

#1462 Adapt optional StartTrigger in Act (OSC 1.3)
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trigger.hpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/trigger.cpp
Labels: bump patch

#1470 Fix/sonor cloud issue 8-1
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.cpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
Labels: refactor, wait for regression test, bump patch

#1465 Fix/request enable autoware control
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: bump patch

#1258 Feature/time to collision condition
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_speed_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/time_to_collision_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/time_to_collision_condition_target.hpp
  openscenario/openscenario_interpreter/src/syntax/entity_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/time_to_collision_condition_target.cpp
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.TimeToCollisionCondition.yaml
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: feature, bump minor

#1481 Feature/multi level lanelet support
  .github/workflows/custom_spell.json
  common/math/geometry/include/geometry/plane.hpp
  common/math/geometry/include/geometry/quaternion/get_angle_difference.hpp
  common/math/geometry/include/geometry/quaternion/get_normal_vector.hpp
  common/math/geometry/src/plane.cpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/entity_status.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_source.hpp
  simulation/traffic_simulator/src/data_type/entity_status.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic/traffic_source.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/helper_functions.hpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
Labels: bump minor

#1475 Fix bug in `math::geometry::getClosestPoses`
  common/math/geometry/src/bounding_box.cpp
  common/math/geometry/test/src/test_bounding_box.cpp
Labels: bug, bump patch

#1489 Update Docker.yaml
  .github/workflows/Docker.yaml
Labels: bump patch

#1491 SpellCheckAll and SpellCheck do almost same thing, so merge them.
  .github/workflows/SpellCheck.yaml
  .github/workflows/SpellCheckAll.yaml
Labels: bump patch

#1490 Feature/is in intersection
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
Labels: bump patch

#1488 Refactor/concealer 1
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware.hpp
  external/concealer/include/concealer/autoware_stream.hpp
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/execute.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/include/concealer/has_data_member_allow_goal_modification.hpp
  external/concealer/include/concealer/has_data_member_option.hpp
  external/concealer/include/concealer/launch.hpp
  external/concealer/include/concealer/member_detector.hpp
  external/concealer/include/concealer/service_with_validation.hpp
  external/concealer/include/concealer/subscriber_wrapper.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/autoware.cpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/execute.cpp
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  external/concealer/src/task_queue.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: refactor, bump patch

#1464 RJD-1457/traffic_sink_refactor
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/traffic_sink/CMakeLists.txt
  mock/cpp_mock_scenarios/src/traffic_sink/auto_sink_vehicle.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_module_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_sink.hpp
  simulation/traffic_simulator/src/traffic/traffic_controller.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
Labels: wait for regression test, bump minor

#1498 Fix/canonicalize function
  simulation/traffic_simulator/src/utils/pose.cpp
  simulation/traffic_simulator/test/src/utils/test_pose.cpp
Labels: wait for regression test, bump patch
