Repository tier4/scenario_simulator_v2, pull requests merged in 2024-02, with the labels that each got.

#1150 Feature/real time factor control
  rviz_plugins/real_time_factor_control_rviz_plugin/CMakeLists.txt
  rviz_plugins/real_time_factor_control_rviz_plugin/package.xml
  rviz_plugins/real_time_factor_control_rviz_plugin/plugins/plugin_description.xml
  rviz_plugins/real_time_factor_control_rviz_plugin/src/real_time_factor_slider.cpp
  rviz_plugins/real_time_factor_control_rviz_plugin/src/real_time_factor_slider.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/simulation_clock/simulation_clock.hpp
  simulation/traffic_simulator/src/simulation_clock/simulation_clock.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test

#1077 Fix/autoware shutdown
  common/status_monitor/include/status_monitor/status_monitor.hpp
  common/status_monitor/src/status_monitor.cpp
  external/concealer/package.xml
  external/concealer/src/field_operator_application.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bug

#1184 Feature/consider tread in ego entity
  docs/ReleaseNotes.md
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: bug, feature, wait for regression test

#1185 Feature/new release flow
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_samples/example_detail.md
  .github/pull_request_samples/example_simple.md
  .github/workflows/BuildAndRun.yaml
  .github/workflows/CheckAndCommentAction.yaml
  .github/workflows/CheckBranchUpToDate.yaml
  .github/workflows/CheckLabel.yaml
  .github/workflows/Docker.yaml
  .github/workflows/Documentation.yaml
  .github/workflows/DocumentationLinkCheck.yaml
  .github/workflows/InterfaceUpdateNotification.yaml
  .github/workflows/LineLint.yaml
  .github/workflows/PostCheckList.yaml
  .github/workflows/Release.yaml
  .github/workflows/SimModelUpdateNotification.yaml
  .github/workflows/SpellCheck.yaml
  .github/workflows/SpellCheckAll.yaml
  .github/workflows/SyncReleaseNote.yaml
  .github/workflows/ToolDispatch.yaml
  .github/workflows/custom_spell.json
  CONTRIBUTING.md
  docs/ReleaseNotes.md
  mkdocs.yml
  rviz_plugins/real_time_factor_control_rviz_plugin/package.xml
Labels: bump major

#1191 Fix workflow trigger for CheckLabel.yaml
  .github/workflows/CheckLabel.yaml
Labels: bump patch

#1192 Doc/lane pose calculation
  .github/pull_request_samples/example_detail.md
  docs/developer_guide/lane_pose_calculation/GetLongitudinalDistance.md
  docs/developer_guide/lane_pose_calculation/LanePoseCalculation.md
  docs/developer_guide/lane_pose_calculation/Spawn.md
  docs/developer_guide/lane_pose_calculation/UpdateFrame.md
  docs/image/lane_pose_calculation.png
  docs/image/longitudinal_distance.png
  mkdocs.yml
Labels: bump patch

#1197 Update release.yaml to avoid command substitution on Markdown
  .github/workflows/Release.yaml
Labels: bump patch

#1182 Consider road slope in ego vehicle simulation
  external/concealer/src/autoware_universe.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test, bump minor

#1194 Feature/default matching distance
  docs/developer_guide/lane_pose_calculation/LanePoseCalculation.md
  docs/developer_guide/lane_pose_calculation/Spawn.md
  docs/developer_guide/lane_pose_calculation/UpdateFrame.md
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/pedestrian/pedestrian_action_node.cpp
  simulation/do_nothing_plugin/include/do_nothing_plugin/plugin.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: wait for regression test, bump minor

#1190 Support `PULL_OVER` as minimul risk manuever behavior in `autoware_adapi_v1_msgs/system/msg/MrmState.msg`
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
Labels: wait for regression test, bump minor

#1195 Feature/split rviz packages
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  rviz_plugins/openscenario_visualization/CHANGELOG.rst
  rviz_plugins/openscenario_visualization/CMakeLists.txt
  rviz_plugins/openscenario_visualization/icons/classes/ContextPanel.png
  rviz_plugins/openscenario_visualization/img/rviz.png
  rviz_plugins/openscenario_visualization/include/openscenario_visualization/context_panel_plugin.hpp
  rviz_plugins/openscenario_visualization/include/openscenario_visualization_condition_groups_plugin/jsk_overlay_utils.hpp
  rviz_plugins/openscenario_visualization/include/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.hpp
  rviz_plugins/openscenario_visualization/package.xml
  rviz_plugins/openscenario_visualization/plugins.xml
  rviz_plugins/openscenario_visualization/src/context_panel_plugin.cpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/jsk_overlay_utils.cpp
  rviz_plugins/openscenario_visualization/src/openscenario_visualization_condition_groups_plugin/openscenario_visualization_condition_groups_plugin.cpp
  rviz_plugins/openscenario_visualization/src/ui/context_panel_plugin.ui
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/visualization/visualization_component.hpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
  simulation/traffic_simulator/src/visualization/visualization_node.cpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump patch

#1204 Check message definition updates automatically
  .github/msgs_checker.py
  .github/workflows/CheckMessageDepsUpdate.yaml
  poetry.lock
  pyproject.toml
Labels: small feature, bump patch
