Repository tier4/scenario_simulator_v2, pull requests merged in 2024-08, with the labels that each got.

#1318 add Longitudinal_control.md
  docs/developer_guide/Longitudinal_control.md
  docs/developer_guide/images/Longitudinal_control/synchronizedAction.png
Labels: bump patch

#1339 fix CONFIG_EXTRAS argument of ament_auto_package macro
  mock/cpp_mock_scenarios/CMakeLists.txt
Labels: bump patch

#1345 Avoid false detection of newline character literals by spell check.
  test_runner/random_test_runner/include/random_test_runner/data_types.hpp
Labels: small problem, bump patch

#1316 Support `RelativeClearanceCondition` in OpenSCENARIO XML 1.3
  docs/developer_guide/OpenSCENARIOSupport.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/integer.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_clearance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_lane_range.hpp
  openscenario/openscenario_interpreter/src/syntax/entity_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/integer.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_clearance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_lane_range.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.RelativeClearanceCondition-back.yaml
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.RelativeClearanceCondition.yaml
Labels: bump minor

#1335 feat(traffic_controller, api): add rviz marker for TrafficSink
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_module_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_sink.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/traffic/traffic_controller.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
Labels: small feature, bump patch

#1338 Fix/interpreter/user defined value condition
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/include/concealer/subscriber_wrapper.hpp
  external/concealer/src/autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_value_condition.hpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  test_runner/scenario_test_runner/scenario/ByValueCondition.UserDefinedValueCondition.yaml
Labels: bug, bump patch

#1340 Rjd 1278/traffic simulator update
  simulation/traffic_simulator/test/src/helper/test_helper.cpp
  simulation/traffic_simulator/test/src/simulation_clock/test_simulation_clock.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
Labels: bump patch

#1351 use workflow dispatch in docker build
  .github/workflows/Docker.yaml
  .github/workflows/Release.yaml
Labels: bump patch

#1348 Fix longitudinal dintance calculation with lane-change in `HdMapUtils::getLongitudinalDistance`
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.DistanceCondition.Shortest.yaml
Labels: bug, bump patch

#1354 Fix follow trajectory action and timestamp in entity status
  simulation/do_nothing_plugin/src/plugin.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: wait for regression test, bump patch

#1356 Remove unused data members: current_time step_time
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/behavior_tree.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/behavior_tree.hpp
  simulation/behavior_tree_plugin/src/pedestrian/behavior_tree.cpp
  simulation/behavior_tree_plugin/src/vehicle/behavior_tree.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/longitudinal_speed_planning.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/behavior/longitudinal_speed_planning.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: bump patch

#1358 Remove unused data members: npc_logic_started
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/test/src/entity/test_misc_object_entity.cpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
Labels: bump patch
