Repository tier4/scenario_simulator_v2, pull requests merged in 2024-04, with the labels that each got.

#1224 remove // headers in STL comment
  docs/developer_guide/TrafficSimulator.md
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/src/behavior_plugin/load_do_nothing_plugin.cpp
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/follow_lane/follow_with_offset.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_lateral_velocity.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_time.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_time.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_step.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_limit.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_linear.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_relative.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
Labels: bump patch

#1225 fix -Wreorder warnings in test extcutor class
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
Labels: bump patch

#1222 Feature/user defined controller
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/controller.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/object_controller.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/add_entity_action.cpp
  openscenario/openscenario_interpreter/src/syntax/controller.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
  test_runner/scenario_test_runner/scenario/all-in-one.yaml
  test_runner/scenario_test_runner/scenario/catalog/controller/all-in-one-controller.yaml
  test_runner/scenario_test_runner/scenario/sample.yaml
Labels: bump minor

#1216 Implement `DistanceCondition` / `RelativeDistanceCondition` for `shortest` of `RoutingAlgorithm`
  docs/developer_guide/DistanceCalculation.md
  docs/image/looped_map_routing.png
  docs/image/shortest_l1_dash.png
  docs/image/shortest_l3.png
  docs/image/shortest_typical_routing.png
  mkdocs.yml
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/coordinate_system.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/entity_ref.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/position.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/relative_distance_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/routing_algorithm.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/rule.hpp
  openscenario/openscenario_interpreter/src/syntax/distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/relative_distance_type.cpp
  openscenario/openscenario_interpreter/src/syntax/routing_algorithm.cpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/lanelet_pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/cache.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/src/data_type/lanelet_pose.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/scenario/ByEntityCondition.EntityCondition.DistanceCondition.Shortest.yaml
Labels: wait for regression test, bump minor

#1229 add follow trajectory action in do_nothing_plugin
  common/math/geometry/include/geometry/linear_algebra.hpp
  common/math/geometry/src/linear_algebra.cpp
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_trajectory/CMakeLists.txt
  mock/cpp_mock_scenarios/src/follow_trajectory/follow_polyline_trajectory_with_do_nothing_plugin.cpp
  simulation/do_nothing_plugin/include/do_nothing_plugin/plugin.hpp
  simulation/do_nothing_plugin/src/plugin.cpp
Labels: bump minor

#1223 Delete workflow feature and add alternative bash script
  .github/workflows/BuildAndRun.yaml
  .github/workflows/workflow.sh
  openscenario/openscenario_utility/openscenario_utility/scenario_validation.py
  test_runner/scenario_test_runner/config/workflow.txt
  test_runner/scenario_test_runner/config/workflow_example.yaml
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
  test_runner/scenario_test_runner/scenario_test_runner/workflow.py
Labels: wait for regression test, bump minor

#1227 Exclude LiDAR occluded object on OccupancyGrid
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/occupancy_grid/occupancy_grid_sensor.cpp
Labels: wait for regression test, bump patch

#1232 Update scenario_test_runner.launch.py
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump patch

#1112 Fix/Standstill duration condition for MiscObjects
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
Labels: bump patch
