Repository tier4/scenario_simulator_v2, pull requests merged in 2024-01, with the labels that each got.

#1166 fix document about OpenSCEANRIO
  docs/developer_guide/OpenSCENARIOSupport.md
  docs/user_guide/scenario_test_runner/ScenarioTestRunner.md
Labels: bug

#1168 Feature/get stop line ids
  docs/ReleaseNotes.md
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light_manager.hpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_manager.cpp
Labels: bug, feature, wait for regression test

#1174 Feature/scenario test
  .github/workflows/BuildAndRun.yaml
Labels: github actions
