Repository tier4/scenario_simulator_v2, pull requests merged in 2024-07, with the labels that each got.

#1262 Add traffic light publisher for external services
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/traffic_lights/traffic_light_publisher.cpp
  simulation/traffic_simulator_msgs/CMakeLists.txt
  simulation/traffic_simulator_msgs/msg/TrafficLightArrayV1.msg
  simulation/traffic_simulator_msgs/msg/TrafficLightBulbV1.msg
  simulation/traffic_simulator_msgs/msg/TrafficLightV1.msg
Labels: wait for regression test, interface breaking, bump minor

#1307 Remove incorrect comment `// headers in STL`
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action_with_speed.cpp
Labels: bump patch

#1305 Feature/publish empty context
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test, bump minor

#1317 Feature/docker tag
  .github/workflows/Docker.yaml
  .github/workflows/Release.yaml
Labels: bump patch

#1322 update README.md
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: bump patch

#1319 fix: Change map of synchronized action's test
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action_with_speed.cpp
Labels: bump patch

#1309 feat: use autoware_lanelet2_extension instead of lanelet2_extension
  dependency_humble.repos
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  test_runner/random_test_runner/src/lanelet_utils.cpp
Labels: wait for regression test, bump minor

#1323 Fill x/y value when spawning entity in map frame.
  mock/cpp_mock_scenarios/CMakeLists.txt
  mock/cpp_mock_scenarios/src/spawn/CMakeLists.txt
  mock/cpp_mock_scenarios/src/spawn/spawn_in_map_frame.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
Labels: wait for regression test, bump minor

#1325 Feature/interpreter/lidar configuration
  docs/developer_guide/ConfiguringPerceptionTopics.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
  test_runner/scenario_test_runner/scenario/Property.pointcloudVerticalFieldOfView.yaml
Labels: bump minor

#1327 Update OpenSCENARIOSupport.md
  .github/workflows/custom_spell.json
  docs/developer_guide/OpenSCENARIOSupport.md
Labels: documentation, bump patch

#1321 feat: [RJD-1199] add imu sensor to simple sensor simulator
  docs/developer_guide/Communication.md
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/imu/imu_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/simple_sensor_simulator.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/imu/imu_sensor.cpp
  simulation/simple_sensor_simulator/src/sensor_simulation/sensor_simulation.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/proto/simulation_api_schema.proto
  simulation/simulation_interface/src/zmq_multi_client.cpp
  simulation/simulation_interface/src/zmq_multi_server.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/src/api/api.cpp
Labels: bump minor
