Repository tier4/scenario_simulator_v2, pull requests merged in 2024-09, with the labels that each got.

#1301 Test: [RJD-937] to Implement Unit tests on simple_sensor_simulator
  simulation/simple_sensor_simulator/test/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_raycaster.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_raycaster.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_box.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_primitive.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_primitive.hpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/primitives/test_vertex.cpp
  simulation/simple_sensor_simulator/test/src/utils/expect_eq_macros.hpp
  simulation/simple_sensor_simulator/test/src/utils/helper_functions.hpp
Labels: bump patch

#1353 Rjd 1278/fix line segment
  common/math/geometry/include/geometry/polygon/line_segment.hpp
  common/math/geometry/src/intersection/intersection.cpp
  common/math/geometry/src/polygon/line_segment.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  common/math/geometry/test/test_intersection.cpp
  common/math/geometry/test/test_line_segment.cpp
Labels: wait for regression test, bump minor

#1362 Feature/ros2 parameter forwarding
  external/concealer/include/concealer/launch.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/configuration.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump minor

#1341 Rjd 1278/geometry update
  common/math/geometry/test/CMakeLists.txt
  common/math/geometry/test/src/expect_eq_macros.hpp
  common/math/geometry/test/src/intersection/CMakeLists.txt
  common/math/geometry/test/src/intersection/test_collision.cpp
  common/math/geometry/test/src/intersection/test_intersection.cpp
  common/math/geometry/test/src/polygon/CMakeLists.txt
  common/math/geometry/test/src/polygon/test_line_segment.cpp
  common/math/geometry/test/src/polygon/test_polygon.cpp
  common/math/geometry/test/src/quaternion/CMakeLists.txt
  common/math/geometry/test/src/quaternion/test_quaternion.cpp
  common/math/geometry/test/src/solver/CMakeLists.txt
  common/math/geometry/test/src/solver/test_polynomial_solver.cpp
  common/math/geometry/test/src/spline/CMakeLists.txt
  common/math/geometry/test/src/spline/test_catmull_rom_spline.cpp
  common/math/geometry/test/src/spline/test_catmull_rom_subspline.cpp
  common/math/geometry/test/src/spline/test_hermite_curve.cpp
  common/math/geometry/test/src/test_bounding_box.cpp
  common/math/geometry/test/src/test_distance.cpp
  common/math/geometry/test/src/test_transform.cpp
  common/math/geometry/test/src/test_utils.hpp
  common/math/geometry/test/src/vector3/CMakeLists.txt
  common/math/geometry/test/src/vector3/test_truncate_custom.cpp
  common/math/geometry/test/src/vector3/test_truncate_msg.cpp
  common/math/geometry/test/src/vector3/test_vector3.cpp
  common/math/geometry/test/test_line_segment.cpp
Labels: bump patch

#1368 fix: mock test launch
  mock/cpp_mock_scenarios/include/cpp_mock_scenarios/cpp_scenario_node.hpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
Labels: bump patch

#1375 fix `architecture_type` in documentation
  docs/user_guide/QuickStart.md
Labels: documentation, bump patch

#1373 fix: install add_cpp_mock_scenario_test.cmake first, or colcon build won't pass
  mock/cpp_mock_scenarios/CMakeLists.txt
Labels: bump patch

#1366 RJD-1197/distance
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/test/CMakeLists.txt
  simulation/traffic_simulator/test/map/intersection/lanelet2_map.osm
  simulation/traffic_simulator/test/map/standard_map/lanelet2_map.osm
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/helper_functions.hpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_light_manager.cpp
  simulation/traffic_simulator/test/src/utils/CMakeLists.txt
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
Labels: wait for regression test, bump patch

#1324 Fix/fix eigen variable definition
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
Labels: wait for regression test, bump patch

#1388 Use `base_link` for default imu `frame_id`
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
Labels: wait for regression test, bump patch

#1369 Fix/acquire position action
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/src/syntax/storyboard_element_state_condition.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  test_runner/scenario_test_runner/scenario/RoutingAction.AcquirePositionAction-continuous.yaml
Labels: wait for regression test, bump patch

#1397 [RJD-1201] Fix QuickStart.md
  docs/user_guide/QuickStart.md
Labels: documentation, bump patch

#1390 Feature/lcov
  .github/workflows/BuildAndRun.yaml
Labels: bump patch

#1399 Update custom_spell.json
  .github/workflows/custom_spell.json
Labels: bump patch

#1398 Feature/sonar cloud
  .github/workflows/BuildAndRun.yaml
  .github/workflows/custom_spell.json
  sonar-project.properties
Labels: bump patch
