Repository tier4/scenario_simulator_v2, pull requests merged in 2024-10, with the labels that each got.

#1405 Test for cmake RelWithDebInfo build type
  .github/workflows/BuildAndRun.yaml
  .github/workflows/Release.yaml
  openscenario/openscenario_interpreter/src/syntax/relative_clearance_condition.cpp
Labels: bump patch

#1407 update Dockerfile
  Dockerfile
Labels: bump patch

#1408 Feature/joblist update traveled distance
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/test/src/entity/test_misc_object_entity.cpp
Labels: wait for regression test, bump patch

#1378 Use `/autoware/state` to get autoware state
  docs/developer_guide/Communication.md
  external/concealer/include/concealer/field_operator_application_for_autoware_universe.hpp
  external/concealer/package.xml
  external/concealer/src/field_operator_application_for_autoware_universe.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
Labels: wait for regression test, bump patch

#1409 Register StandStillDuration to job list
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/misc_object_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/test/src/entity/test_misc_object_entity.cpp
Labels: wait for regression test, bump patch

#1370 Reducing build time of `openscenario_interpreter` by utilizing precompiled headers
  openscenario/openscenario_interpreter/CMakeLists.txt
Labels: small feature, improvement, bump patch

#1361 fix(cpp_mock_scenarios, ego_entity_simulation): fix ego issue in random001, fix getCurrentPose()
  common/math/geometry/include/geometry/quaternion/get_rotation_matrix.hpp
  mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
Labels: bug, wait for regression test, bump patch

#1420 Added checks for negative discriminants
  simulation/traffic_simulator/src/behavior/longitudinal_speed_planning.cpp
Labels: wait for regression test, bump patch

#1417 Fix/remove warnings from sonarcloud
  common/math/geometry/include/geometry/bounding_box.hpp
  common/math/geometry/include/geometry/polygon/line_segment.hpp
  common/math/geometry/include/geometry/spline/hermite_curve.hpp
  common/math/geometry/src/distance.cpp
  common/math/geometry/src/intersection/collision.cpp
  common/math/geometry/src/polygon/line_segment.cpp
  common/math/geometry/src/polygon/polygon.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  common/math/geometry/src/spline/hermite_curve.cpp
Labels: wait for regression test, bump patch

#1418 Introduce Boost.JSON as a JSON serialization library
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/act.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/action.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/condition_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/event.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/init_actions.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/maneuver_group.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/open_scenario.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/private.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/scenario_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/story.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/storyboard.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/trigger.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_constraint_group.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  openscenario/openscenario_interpreter/src/syntax/act.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/condition.cpp
  openscenario/openscenario_interpreter/src/syntax/condition_group.cpp
  openscenario/openscenario_interpreter/src/syntax/event.cpp
  openscenario/openscenario_interpreter/src/syntax/init.cpp
  openscenario/openscenario_interpreter/src/syntax/init_actions.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver.cpp
  openscenario/openscenario_interpreter/src/syntax/maneuver_group.cpp
  openscenario/openscenario_interpreter/src/syntax/open_scenario.cpp
  openscenario/openscenario_interpreter/src/syntax/private.cpp
  openscenario/openscenario_interpreter/src/syntax/scenario_definition.cpp
  openscenario/openscenario_interpreter/src/syntax/story.cpp
  openscenario/openscenario_interpreter/src/syntax/storyboard.cpp
  openscenario/openscenario_interpreter/src/syntax/trigger.cpp
Labels: improvement, wait for regression test, bump patch

#1425 Fix Arm Docker Build Support
  .github/workflows/Docker.yaml
  Dockerfile.arm64
Labels: bump patch

#1427 Improved readability.​
  common/math/geometry/src/bounding_box.cpp
  common/math/geometry/src/intersection/intersection.cpp
Labels: wait for regression test, bump patch
