Repository tier4/scenario_simulator_v2, pull requests merged in 2025-03, with the labels that each got.

#1539 RJD-1057: Reorganize ostream operators
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/data_type/lanelet_pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/ostream_helpers.hpp
  simulation/traffic_simulator/src/helper/helper.cpp
  simulation/traffic_simulator/src/helper/ostream_helpers.cpp
  simulation/traffic_simulator/test/src/helper/test_helper.cpp
Labels: refactor, wait for regression test, bump patch

#1532 Feature/simple sensor simulator/new noise model
  docs/developer_guide/.pages
  docs/developer_guide/Parameters.md
  external/concealer/include/concealer/get_parameter.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  test_runner/scenario_test_runner/config/parameters.yaml
Labels: feature, wait for regression test, bump minor

#1541 fix: the noises are not initialized in detection_sensor's noise_v2
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
Labels: bug, bump patch

#1542 feat: disable the localization noises when ego speed is slow
  external/concealer/include/concealer/publisher.hpp
  external/concealer/src/publisher.cpp
  test_runner/scenario_test_runner/config/parameters.yaml
Labels: small feature, wait for regression test, bump patch

#1355 feat: add new vehicle model
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/ego_entity_simulation.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/vehicle_model/sim_model_delay_steer_acc_geared_wo_fall_guard.cpp
Labels: feature, bump minor

#1534 Refactor/concealer 4
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/task_queue.hpp
  external/concealer/include/concealer/transition_assertion.hpp
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/task_queue.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: refactor, bump patch

#1537 export statistics from `ExecutionTimer` class to JSON file
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/execution_timer.hpp
Labels: feature, bump minor

#1548 Add missing debug marker for motion velocity planner
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
Labels: bump patch

#1419 Reduce build time by suppressing template instantiation
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/attribute.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/element.hpp
  openscenario/openscenario_interpreter/src/reader/attribute.cpp
  openscenario/openscenario_interpreter/src/reader/element.cpp
  openscenario/openscenario_interpreter/src/syntax/action.cpp
  openscenario/openscenario_interpreter/src/syntax/assign_controller_action.cpp
  openscenario/openscenario_interpreter/src/syntax/assign_route_action.cpp
  openscenario/openscenario_interpreter/src/syntax/by_value_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/collision_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/condition.cpp
  openscenario/openscenario_interpreter/src/syntax/deterministic_parameter_distribution.cpp
  openscenario/openscenario_interpreter/src/syntax/deterministic_single_parameter_distribution_type.cpp
  openscenario/openscenario_interpreter/src/syntax/distribution_definition.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_action.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_condition.cpp
  openscenario/openscenario_interpreter/src/syntax/entity_object.cpp
  openscenario/openscenario_interpreter/src/syntax/environment_action.cpp
  openscenario/openscenario_interpreter/src/syntax/global_action.cpp
  openscenario/openscenario_interpreter/src/syntax/lane_change_target.cpp
  openscenario/openscenario_interpreter/src/syntax/lateral_action.cpp
  openscenario/openscenario_interpreter/src/syntax/longitudinal_action.cpp
  openscenario/openscenario_interpreter/src/syntax/modify_rule.cpp
  openscenario/openscenario_interpreter/src/syntax/object_controller.cpp
  openscenario/openscenario_interpreter/src/syntax/open_scenario_category.cpp
  openscenario/openscenario_interpreter/src/syntax/parameter_action.cpp
  openscenario/openscenario_interpreter/src/syntax/position.cpp
  openscenario/openscenario_interpreter/src/syntax/private_action.cpp
  openscenario/openscenario_interpreter/src/syntax/routing_action.cpp
  openscenario/openscenario_interpreter/src/syntax/selected_entities.cpp
  openscenario/openscenario_interpreter/src/syntax/shape.cpp
  openscenario/openscenario_interpreter/src/syntax/speed_action_target.cpp
  openscenario/openscenario_interpreter/src/syntax/stochastic_distribution_type.cpp
  openscenario/openscenario_interpreter/src/syntax/time_reference.cpp
  openscenario/openscenario_interpreter/src/syntax/time_to_collision_condition_target.cpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_action.cpp
  openscenario/openscenario_interpreter/src/syntax/trajectory_ref.cpp
Labels: wait for regression test, bump patch

#1538 HdMapUtils refactor `lanelet_wrapper::distance::distanceToStopLine`
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/lanelet_map.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/lanelet_wrapper.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/distance.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/lanelet_map.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
Labels: refactor, wait for regression test, bump major

#1546 Refactor/concealer 5
  common/get_parameter/CMakeLists.txt
  common/get_parameter/include/get_parameter/get_parameter.hpp
  common/get_parameter/package.xml
  common/get_parameter/src/main.cpp
  external/concealer/include/concealer/publisher.hpp
  external/concealer/include/concealer/subscriber.hpp
  external/concealer/package.xml
  external/concealer/src/field_operator_application.cpp
  external/concealer/src/path_with_lane_id.cpp
  external/concealer/src/publisher.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/cmath/hypot.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simple_sensor_simulator/src/simple_sensor_simulator.cpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/ego_entity_simulation.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/node_parameters.hpp
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: refactor, wait for regression test, bump major

#1536 Make Certain Member Functions Public for context_gamma_planner
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_lights_base.hpp
Labels: bump patch

#1540 RJD-1057: Change order of functions / variables
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: wait for regression test, bump patch

#1547 Refactor/concealer 6
  external/concealer/include/concealer/member_detector.hpp
  external/concealer/include/concealer/service.hpp
  external/concealer/src/field_operator_application.cpp
Labels: refactor, bump patch

#1553 Renamed getStopLineIds to stopLineIds to revive functionality.
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/lanelet_map.hpp
  simulation/traffic_simulator/src/lanelet_wrapper/lanelet_map.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
Labels: bump minor

#1550 HdMapUtils refactor `lanelet_wrapper::traffic_lights`
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/traffic_lights.hpp
  simulation/traffic_simulator/src/lanelet_wrapper/traffic_lights.cpp
Labels: feature, wait for regression test, bump minor

#1552 RJD-1057: Remove some entity type specific functions in EntityManager
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: bump patch

#1543 RJD-1057: Unify spawn API
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
Labels: wait for regression test, bump patch

#1549 Refactor/concealer 7
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/legacy_autoware_state.hpp
  external/concealer/src/field_operator_application.cpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: refactor, bump patch

#1551 HdMapUtils refactor `lanelet_wrapper::distance::lateralDistance`
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/distance.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
Labels: refactor, wait for regression test, bump major
