Repository tier4/scenario_simulator_v2, pull requests merged in 2025-08, with the labels that each got.

#1559 HdMapUtils refactor `lanelet_wrapper::distance::longitudinalDistance`
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/pedestrian/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_trajectory.hpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/routing_configuration.hpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/pose.hpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/distance.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
  simulation/traffic_simulator/test/src/utils/test_pose.cpp
Labels: refactor, bump major

#1661 fix(concealer): fix spinner thread start timing
  external/concealer/include/concealer/autoware_universe.hpp
Labels: bug, bump patch

#1663 Fix AWSIM documentation link
  docs/user_guide/random_test_runner/QuickStart.md
Labels: documentation, bump patch

#1664 refactor: change planning output topic name to /planning/trajectory
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
Labels: bump patch
