Repository tier4/scenario_simulator_v2, pull requests merged in 2025-05, with the labels that each got.

#1591 Avoid link check error
  .github/workflows/DocumentationLinkCheck.yaml
Labels: bump patch

#1588 Fix missing RViz config file and duplicate node issues
  common/get_parameter/include/get_parameter/get_parameter.hpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
  test_runner/random_test_runner/launch/random_test.launch.py
  test_runner/random_test_runner/test/test_test_executor.cpp
Labels: bug, bump patch

#1586 Add arm64 build test
  .github/workflows/BuildAndRun.yaml
Labels: bump patch

#1596 fix push tag position
  .github/workflows/Docker.yaml
Labels: bump patch

#1600 remove DispatchTrigger.yaml
  .github/workflows/DispatchTrigger.yaml
Labels: bump patch

#1598 fix: preload agnocast only when agnocast is enabled
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bug, bump patch

#1579 [FIX] Lanelet matching with absolute distance
  simulation/traffic_simulator/src/lanelet_wrapper/pose.cpp
Labels: bump patch

#1590 Specify `allow_goal_modification` option to goal via `AcquirePositionAction.allow_goal_modification` parameter
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/src/field_operator_application.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/properties.hpp
  openscenario/openscenario_interpreter/src/syntax/acquire_position_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/data_type/route_option.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
  simulation/traffic_simulator/test/src/entity/test_misc_object_entity.cpp
  test_runner/scenario_test_runner/scenario/RoutingAction.AcquirePositionAction-allow_goal_modification.yaml
Labels: bump minor

#1609 Feature/delay curventure calculation
  common/math/geometry/include/geometry/solver/polynomial_solver.hpp
  common/math/geometry/include/geometry/spline/catmull_rom_spline.hpp
  common/math/geometry/include/geometry/vector3/operator.hpp
  common/math/geometry/src/polygon/line_segment.cpp
  common/math/geometry/src/spline/catmull_rom_spline.cpp
  common/math/geometry/src/spline/hermite_curve.cpp
  common/math/geometry/test/src/polygon/test_line_segment.cpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  simulation/do_nothing_plugin/src/plugin.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: wait for regression test, bump patch

#1612 Refactor ActionNode to isolate side effects via pure virtual methods
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_lane_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_trajectory_sequence/follow_polyline_trajectory_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/walk_straight_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_front_entity_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_lane_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/move_backward_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_stop_line_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/stop_at_traffic_light_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/yield_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/lane_change_action.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/pedestrian/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/pedestrian/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/behavior_tree_plugin/src/pedestrian/walk_straight_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/move_backward_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_crossing_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_stop_line_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/stop_at_traffic_light_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/yield_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_trajectory_sequence/follow_polyline_trajectory_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/lane_change_action.cpp
Labels: bump patch
