Repository tier4/scenario_simulator_v2, pull requests merged in 2025-07, with the labels that each got.

#1633 Add noise model v3 for perception topic
  common/get_parameter/include/get_parameter/get_parameter.hpp
  docs/developer_guide/Parameters.md
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/operators.hpp
  simulation/simulation_interface/src/operators.cpp
  test_runner/scenario_test_runner/config/parameters.yaml
Labels: bump minor

#1640 Delete HowToWriteWorkflowFile.md
  docs/user_guide/scenario_test_runner/.pages
  docs/user_guide/scenario_test_runner/HowToWriteWorkflowFile.md
  docs/user_guide/scenario_test_runner/ScenarioTestRunner.md
Labels: bump patch

#1631 Refactor bad-mannered things
  common/scenario_simulator_exception/package.xml
  common/simple_junit/package.xml
  common/status_monitor/package.xml
  map/kashiwanoha_map/package.xml
  map/simple_cross_map/package.xml
  mock/cpp_mock_scenarios/package.xml
  openscenario/openscenario_experimental_catalog/package.xml
  openscenario/openscenario_interpreter/package.xml
  openscenario/openscenario_interpreter_example/package.xml
  openscenario/openscenario_interpreter_msgs/package.xml
  openscenario/openscenario_preprocessor_msgs/package.xml
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/imu/imu_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/occupancy_grid/occupancy_grid_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/primitives/box.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/test/src/utils/helper_functions.hpp
  simulation/simulation_interface/CMakeLists.txt
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/simulation_interface/include/simulation_interface/operators.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_client.hpp
  simulation/simulation_interface/include/simulation_interface/zmq_multi_server.hpp
  simulation/simulation_interface/test/expect_equal_macros.hpp
  simulation/simulation_interface/test/test_conversions.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/helper/helper.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_light.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic_lights/traffic_lights_base.hpp
  simulation/traffic_simulator/package.xml
  test_runner/random_test_runner/package.xml
Labels: bump patch

#1634 Use ament_vendor for zmqpp library
  external/zmqpp_vendor/CMakeLists.txt
  external/zmqpp_vendor/package.xml
  external/zmqpp_vendor/patches/zmqpp_export.patch
  external/zmqpp_vendor/zmqpp_vendor-extras.cmake
Labels: bump patch

#1644 Initialize twist/accel values to zero in DoNothingBehavior when not following trajectory
  simulation/do_nothing_plugin/src/plugin.cpp
Labels: bump patch

#1635 fix(detection_sensor): setting correct orientation_availability
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
Labels: bump patch

#1655 Disable sonar cloud step in pull-request from external forks
  .github/workflows/BuildAndRun.yaml
Labels: github actions, bump patch

#1648 fix bool conversion issue
  openscenario/openscenario_utility/openscenario_utility/conversion.py
Labels: bump patch

#1650 Transverse mercator projection support
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/package.xml
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/lanelet_loader.cpp
  simulation/traffic_simulator/test/src/hdmap_utils/test_hdmap_utils.cpp
Labels: feature, bump minor

#1654 Support V2I(vehicle to infrastructure) traffic signal in `TrafficSignalState`
  openscenario/openscenario_interpreter/CMakeLists.txt
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/traffic_signal_state.hpp
  openscenario/openscenario_interpreter/src/syntax/traffic_signal_state.cpp
  openscenario/openscenario_interpreter/test/test_parsed_traffic_signal_id.cpp
  test_runner/scenario_test_runner/scenario/TrafficSignalControllerAction.yaml
Labels: bump minor
