Repository tier4/scenario_simulator_v2, pull requests merged in 2025-10, with the labels that each got.

#1689 modify BuildAndRun workflow to avoid `No space left on device` error
  .github/workflows/BuildAndRun.yaml
Labels: bump patch, github_actions

#1688 Replace rclcpp::spin_some
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  rviz_plugins/openscenario_visualization/include/openscenario_visualization/context_panel_plugin.hpp
  rviz_plugins/openscenario_visualization/src/context_panel_plugin.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.hpp
  simulation/traffic_simulator/test/src/traffic_lights/common_test_fixtures.hpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_common.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_v2i.cpp
  simulation/traffic_simulator/test/src/traffic_lights/test_traffic_lights_internal_v2i_new_architecture.cpp
Labels: bump patch

#1684 getTimeRequirementForNonAcceleration step time rounding fix
  simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
Labels: bug, bump patch

#1691 Whole new front entity detection logic
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/action_node.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_front_entity_action.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/vehicle/follow_lane_sequence/follow_lane_action.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_front_entity_action.cpp
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
  simulation/traffic_simulator/include/traffic_simulator/visualization/visualization_component.hpp
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump minor

#1692 Fix Docker build workflow trigger
  .github/workflows/Docker.yaml
Labels: github actions, bump patch
