Repository tier4/scenario_simulator_v2, pull requests merged in 2025-04, with the labels that each got.

#1554 Add remote context_gamma_planner build test.
  .github/workflows/DispatchTrigger.yaml
Labels: bump patch

#1555 Remove Autoware trajectory subscription
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/src/field_operator_application.cpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
Labels: bump patch

#1558 fix: a small bug about turn indicator
  external/concealer/src/autoware_universe.cpp
Labels: bug, bump patch

#1561 Add `override_parameters` argument to `scenario_test_runner`
  openscenario/openscenario_preprocessor/include/openscenario_preprocessor/openscenario_preprocessor.hpp
  openscenario/openscenario_preprocessor/src/openscenario_preprocessor.cpp
  openscenario/openscenario_preprocessor_msgs/CMakeLists.txt
  openscenario/openscenario_preprocessor_msgs/srv/SetParameter.srv
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
  test_runner/scenario_test_runner/scenario_test_runner/scenario_test_runner.py
Labels: bump minor

#1575 add zmqpp vendor package to the depends
  .gitignore
  external/zmqpp_vendor/.github/workflows/BloomRelease.yaml
  external/zmqpp_vendor/.github/workflows/Build.yaml
  external/zmqpp_vendor/.github/workflows/Release.yaml
  external/zmqpp_vendor/CHANGELOG.rst
  external/zmqpp_vendor/CMakeLists.txt
  external/zmqpp_vendor/CONTRIBUTING.md
  external/zmqpp_vendor/LICENSE
  external/zmqpp_vendor/README.md
  external/zmqpp_vendor/package.xml
Labels: bump patch

#1574 Fix/concealer/engage
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
Labels: bug, bump patch

#1334 RJD-1057 (4/5): Remove non-API member functions: EntityManager’s member functions forwarded to EntityBase (2/2)
  mock/cpp_mock_scenarios/src/behavior_plugin/load_do_nothing_plugin.cpp
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/follow_lane/follow_with_offset.cpp
  mock/cpp_mock_scenarios/src/follow_trajectory/follow_polyline_trajectory_with_do_nothing_plugin.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_lateral_velocity.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_time.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_time.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_step.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_limit.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_linear.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_relative.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action_with_speed.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_delay.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_high_rate.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_large.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_mixed.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_multiple.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_outside_lane.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_pedestrian.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_vehicle.cpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/misc_object_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/pedestrian_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/vehicle_entity.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/entity/pedestrian_entity.cpp
  simulation/traffic_simulator/src/entity/vehicle_entity.cpp
Labels: refactor, wait for regression test, bump major

#1566 Feature/pedestrian awareness
  docs/developer_guide/NPCBehavior.md
  openscenario/openscenario_interpreter/src/syntax/add_entity_action.cpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_lane_action.hpp
  simulation/behavior_tree_plugin/package.xml
  simulation/behavior_tree_plugin/src/pedestrian/follow_lane_action.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: wait for regression test, bump minor

#1580 fix(openscenario_interpreter): Prevent data race in callback and get()
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
Labels: bug, bump patch

#1576 fix(docs): use architecture_type:=awf/universe/20250130
  docs/developer_guide/Communication.md
  docs/user_guide/QuickStart.md
  docs/user_guide/random_test_runner/QuickStart.md
  docs/user_guide/random_test_runner/Usage.md
  docs/user_guide/scenario_test_runner/RealtimeFactor.md
Labels: documentation, bump patch

#1582 Fix/concealer 7
  external/concealer/include/concealer/legacy_autoware_state.hpp
  external/concealer/src/field_operator_application.cpp
Labels: bug, bump patch

#1585 Update pedestrian consideration to factor in distance from ego vehicle
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_lane_action.hpp
  simulation/behavior_tree_plugin/src/pedestrian/follow_lane_action.cpp
Labels: wait for regression test, bump minor

#1569 RJD-1681 - add agnocast_wrapper, use agnocast for /perception/obstacle_segmentation/pointcloud
  .github/workflows/custom_spell.json
  common/agnocast_wrapper/CHANGELOG.rst
  common/agnocast_wrapper/CMakeLists.txt
  common/agnocast_wrapper/cmake/agnocast_wrapper_setup_target.cmake
  common/agnocast_wrapper/include/agnocast_wrapper/agnocast_wrapper.hpp
  common/agnocast_wrapper/package.xml
  dependency_humble.repos
  simulation/simple_sensor_simulator/CMakeLists.txt
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/lidar/lidar_sensor.hpp
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/sensor_simulation.hpp
  simulation/simple_sensor_simulator/launch/scenario_simulator.launch
  simulation/simple_sensor_simulator/package.xml
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/CMakeLists.txt
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.cpp
  simulation/simple_sensor_simulator/test/src/sensor_simulation/lidar/test_lidar_sensor.hpp
  simulation/simulation_interface/include/simulation_interface/conversions.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/behavior_plugin_base.hpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: feature, bump minor
