Repository tier4/scenario_simulator_v2, pull requests merged in 2025-01, with the labels that each got.

#1501 chore: update rviz config based on autoware.rviz
  simulation/traffic_simulator/config/scenario_simulator_v2.rviz
Labels: bump patch

#1499 fix(traffic_light): don't call addTrafficLight() when the traffic light id has already existed in map
  simulation/traffic_simulator/src/traffic_lights/traffic_lights_base.cpp
Labels: wait for regression test, bump patch

#1497 Refactor/concealer 2
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/publisher.hpp
  external/concealer/include/concealer/service.hpp
  external/concealer/include/concealer/subscriber.hpp
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/field_operator_application.cpp
  openscenario/openscenario_interpreter/src/syntax/user_defined_value_condition.cpp
  simulation/traffic_simulator/include/traffic_simulator/entity/ego_entity.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/src/entity/ego_entity.cpp
  simulation/traffic_simulator/src/entity/entity_base.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
Labels: refactor, bump patch

#1502 add despawn_function argument
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_controller.hpp
  simulation/traffic_simulator/include/traffic_simulator/traffic/traffic_sink.hpp
  simulation/traffic_simulator/src/traffic/traffic_controller.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
Labels: wait for regression test, bump patch

#1504 chore: fix iclude guards and update xsd comments
  openscenario/openscenario_interpreter/include/openscenario_interpreter/reader/evaluate.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic_multi_parameter_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic_multi_parameter_distribution_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic_parameter_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic_single_parameter_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/deterministic_single_parameter_distribution_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distribution_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distribution_range.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distribution_set.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/distribution_set_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/external_object_reference.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/histogram.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/histogram_bin.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/normal_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_assignment.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_assignments.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_value_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_value_distribution_definition.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/parameter_value_set.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/poisson_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/probability_distribution_set.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/probability_distribution_set_element.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/range.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/stochastic.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/stochastic_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/stochastic_distribution_type.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/uniform_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/user_defined_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/syntax/value_set_distribution.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/type_traits/iterable.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/variant.hpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/utility/visibility.hpp
Labels: bump patch

#1507 RJD-1511/bug_fix
  simulation/behavior_tree_plugin/src/vehicle/follow_lane_sequence/follow_lane_action.cpp
Labels: wait for regression test, bump patch

#1515 Update dependency_humble.repos
  .github/workflows/Docker.yaml
  dependency_humble.repos
  docs/user_guide/QuickStart.md
Labels: bump patch

#1511 RJD-1495/fix
  external/concealer/include/concealer/subscriber.hpp
Labels: wait for regression test, bump patch

#1516 feat(simple_sensor_simulator): use vel state for acc state calculation of SimModelDelaySteerVel
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/vehicle_simulation/vehicle_model/sim_model_delay_steer_vel.hpp
  simulation/simple_sensor_simulator/src/vehicle_simulation/vehicle_model/sim_model_delay_steer_vel.cpp
Labels: bump patch

#1520 chore: update `actions/upload-artifact` in Documentation.yaml
  .github/workflows/Documentation.yaml
Labels: bump patch
