Repository tier4/scenario_simulator_v2, pull requests merged in 2025-02, with the labels that each got.

#1493 Fix/slope inaccuracies
  common/math/geometry/include/geometry/quaternion/norm.hpp
  common/math/geometry/include/geometry/quaternion/normalize.hpp
  common/math/geometry/include/geometry/vector3/operator.hpp
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/traffic_simulator/include/traffic_simulator/utils/pose.hpp
  simulation/traffic_simulator/src/behavior/follow_trajectory.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
Labels: bump minor

#1519 chore: delete unnecessary target branch filter in workflow trigger
  .github/workflows/Documentation.yaml
  .github/workflows/InterfaceUpdateNotification.yaml
  .github/workflows/PostCheckList.yaml
  .github/workflows/SpellCheck.yaml
Labels: bump patch

#1518 Support message type `autoware_internal_planning_msgs::msg::PathWithLaneId`
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/available.hpp
  external/concealer/include/concealer/convert.hpp
  external/concealer/include/concealer/field_operator_application.hpp
  external/concealer/include/concealer/get_parameter.hpp
  external/concealer/include/concealer/path_with_lane_id.hpp
  external/concealer/include/concealer/subscriber.hpp
  external/concealer/package.xml
  external/concealer/src/autoware_universe.cpp
  external/concealer/src/path_with_lane_id.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: feature, wait for regression test, bump minor

#1500 [extra] RJD-1057 (3+/5): change getEntity return type to the reference
  mock/cpp_mock_scenarios/src/behavior_plugin/load_do_nothing_plugin.cpp
  mock/cpp_mock_scenarios/src/collision/crashing_npc.cpp
  mock/cpp_mock_scenarios/src/collision/spawn_with_offset.cpp
  mock/cpp_mock_scenarios/src/cpp_scenario_node.cpp
  mock/cpp_mock_scenarios/src/crosswalk/stop_at_crosswalk.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/accelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_front_entity/decelerate_and_follow.cpp
  mock/cpp_mock_scenarios/src/follow_lane/acquire_position_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/assign_route_in_world_frame.cpp
  mock/cpp_mock_scenarios/src/follow_lane/cancel_request.cpp
  mock/cpp_mock_scenarios/src/follow_lane/follow_with_offset.cpp
  mock/cpp_mock_scenarios/src/follow_trajectory/follow_polyline_trajectory_with_do_nothing_plugin.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_left_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_lateral_velocity.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_linear_time.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_longitudinal_distance.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_right_with_id.cpp
  mock/cpp_mock_scenarios/src/lane_change/lanechange_time.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_in_lane_coordinate_distance.cpp
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  mock/cpp_mock_scenarios/src/merge/merge_left.cpp
  mock/cpp_mock_scenarios/src/metrics/traveled_distance.cpp
  mock/cpp_mock_scenarios/src/move_backward/move_backward.cpp
  mock/cpp_mock_scenarios/src/pedestrian/walk_straight.cpp
  mock/cpp_mock_scenarios/src/random_scenario/random001.cpp
  mock/cpp_mock_scenarios/src/spawn/spawn_in_map_frame.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_continuous_false.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_relative.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_step.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_limit.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_linear.cpp
  mock/cpp_mock_scenarios/src/speed_planning/request_speed_change_with_time_constraint_relative.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action.cpp
  mock/cpp_mock_scenarios/src/synchronized_action/synchronized_action_with_speed.cpp
  mock/cpp_mock_scenarios/src/traffic_simulation_demo.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_delay.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_high_rate.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_large.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_mixed.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_multiple.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_outside_lane.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_pedestrian.cpp
  mock/cpp_mock_scenarios/src/traffic_source/define_traffic_source_vehicle.cpp
  openscenario/openscenario_interpreter/include/openscenario_interpreter/simulator_core.hpp
  simulation/traffic_simulator/include/traffic_simulator/api/api.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_base.hpp
  simulation/traffic_simulator/include/traffic_simulator/entity/entity_manager.hpp
  simulation/traffic_simulator/src/api/api.cpp
  simulation/traffic_simulator/src/entity/entity_manager.cpp
  simulation/traffic_simulator/src/traffic/traffic_sink.cpp
  test_runner/random_test_runner/include/random_test_runner/test_executor.hpp
  test_runner/random_test_runner/test/test_test_executor.cpp
Labels: refactor, bump major

#1496 fix: mock test launch option
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  mock/cpp_mock_scenarios/src/respawn_ego/respawn_ego.cpp
Labels: bump minor

#1525 add comment about respawn_ego scenario
  mock/cpp_mock_scenarios/CMakeLists.txt
Labels: bump patch

#1527 Change copyright date to 2015
  rviz_plugins/real_time_factor_control_rviz_plugin/src/real_time_factor_slider.cpp
  rviz_plugins/real_time_factor_control_rviz_plugin/src/real_time_factor_slider.hpp
  simulation/behavior_tree_plugin/include/behavior_tree_plugin/pedestrian/follow_trajectory_sequence/follow_polyline_trajectory_action.hpp
  simulation/traffic_simulator/include/traffic_simulator/behavior/follow_waypoint_controller.hpp
  simulation/traffic_simulator/src/behavior/follow_waypoint_controller.cpp
Labels: cleanup, bump patch

#1524 feat: implement rosbag storage switching
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: bump minor

#1503 Feature/publisher with customizable randomizer
  docs/developer_guide/.pages
  docs/developer_guide/ConfiguringLocalizationTopics.md
  external/concealer/CMakeLists.txt
  external/concealer/include/concealer/autoware_universe.hpp
  external/concealer/include/concealer/publisher.hpp
  external/concealer/src/publisher.cpp
  external/concealer/test/normal_distribution.cpp
  mock/cpp_mock_scenarios/launch/mock_test.launch.py
  test_runner/scenario_test_runner/config/parameters.yaml
  test_runner/scenario_test_runner/launch/scenario_test_runner.launch.py
Labels: feature, bump minor

#1528 chore: use `AS` instead of `as` in Dockerfiles
  Dockerfile
  Dockerfile.arm64
  Dockerfile.traffic_simulator
Labels: bump patch

#1530 fix: remove double applied orientation for visualization entity triangle marker
  simulation/traffic_simulator/src/visualization/visualization_component.cpp
Labels: bump patch

#1506 Refactor/simple sensor simulator/noise
  simulation/simple_sensor_simulator/include/simple_sensor_simulator/sensor_simulation/detection_sensor/detection_sensor.hpp
  simulation/simple_sensor_simulator/src/sensor_simulation/detection_sensor/detection_sensor.cpp
Labels: refactor, bump patch

#1531 HdMapUtils refactor lanelet_wrapper::route
  simulation/behavior_tree_plugin/src/action_node.cpp
  simulation/traffic_simulator/CMakeLists.txt
  simulation/traffic_simulator/include/traffic_simulator/data_type/lanelet_pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/route.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/pose.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/route.hpp
  simulation/traffic_simulator/src/data_type/lanelet_pose.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/route.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/src/utils/pose.cpp
  simulation/traffic_simulator/test/src/data_type/test_lanelet_pose.cpp
Labels: refactor, wait for regression test, bump major

#1517 Add execution time metrics
  .github/workflows/BuildAndRun.yaml
  .github/workflows/generate_workflow_report.sh
  .github/workflows/workflow.sh
  openscenario/openscenario_interpreter/include/openscenario_interpreter/openscenario_interpreter.hpp
  openscenario/openscenario_interpreter/src/openscenario_interpreter.cpp
  test_runner/scenario_test_runner/config/optional_workflow.txt
  test_runner/scenario_test_runner/scenario/execution_time_test.yaml
Labels: feature, bump minor

#1533 HdMapUtils refactor lanelet_wrapper::lanelet_map::leftBound rightBound
  mock/cpp_mock_scenarios/src/measurement/get_distance_to_lane_bound.cpp
  simulation/traffic_simulator/include/traffic_simulator/hdmap_utils/hdmap_utils.hpp
  simulation/traffic_simulator/include/traffic_simulator/lanelet_wrapper/lanelet_map.hpp
  simulation/traffic_simulator/include/traffic_simulator/utils/distance.hpp
  simulation/traffic_simulator/src/hdmap_utils/hdmap_utils.cpp
  simulation/traffic_simulator/src/lanelet_wrapper/lanelet_map.cpp
  simulation/traffic_simulator/src/utils/distance.cpp
  simulation/traffic_simulator/test/src/utils/test_distance.cpp
Labels: refactor, wait for regression test, bump major
